namespace ZeroAlloc.Resilience.Generator;

using System.Linq;
using System.Text;

internal static class ResilienceWriter
{
    public static string Write(ResilienceModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using ZeroAlloc.Resilience;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();

        if (model.Namespace is not null)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        WriteProxy(sb, model);
        sb.AppendLine();
        WriteDiExtension(sb, model);

        return sb.ToString();
    }

    private static void WriteProxy(StringBuilder sb, ResilienceModel model)
    {
        var hasRetry   = model.Methods.Any(static m => m.Retry is not null);
        var hasTimeout = model.Methods.Any(static m => m.Timeout is not null);
        var hasRate    = model.Methods.Any(static m => m.RateLimit is not null);
        var hasCb      = model.Methods.Any(static m => m.CircuitBreaker is not null);

        sb.AppendLine($"internal sealed class {model.InterfaceName}ResilienceProxy : {model.InterfaceFqn}");
        sb.AppendLine("{");
        sb.AppendLine($"    private readonly {model.InterfaceFqn} _inner;");
        if (hasRetry)   sb.AppendLine("    private readonly global::ZeroAlloc.Resilience.RetryPolicy _retry;");
        if (hasTimeout) sb.AppendLine("    private readonly global::ZeroAlloc.Resilience.TimeoutPolicy _timeout;");
        if (hasRate)    sb.AppendLine("    private readonly global::ZeroAlloc.Resilience.RateLimiter _rateLimiter;");
        if (hasCb)      sb.AppendLine("    private readonly global::ZeroAlloc.Resilience.CircuitBreakerPolicy _circuitBreaker;");
        sb.AppendLine();

        // Constructor
        sb.Append($"    public {model.InterfaceName}ResilienceProxy({model.InterfaceFqn} inner");
        if (hasRetry)   sb.Append(", global::ZeroAlloc.Resilience.RetryPolicy retry");
        if (hasTimeout) sb.Append(", global::ZeroAlloc.Resilience.TimeoutPolicy timeout");
        if (hasRate)    sb.Append(", global::ZeroAlloc.Resilience.RateLimiter rateLimiter");
        if (hasCb)      sb.Append(", global::ZeroAlloc.Resilience.CircuitBreakerPolicy circuitBreaker");
        sb.AppendLine(")");
        sb.AppendLine("    {");
        sb.AppendLine("        _inner = inner;");
        if (hasRetry)   sb.AppendLine("        _retry = retry;");
        if (hasTimeout) sb.AppendLine("        _timeout = timeout;");
        if (hasRate)    sb.AppendLine("        _rateLimiter = rateLimiter;");
        if (hasCb)      sb.AppendLine("        _circuitBreaker = circuitBreaker;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Policy-wrapped methods
        foreach (var method in model.Methods)
            WriteMethod(sb, method);

        // Passthrough methods (no policy — direct delegation)
        foreach (var method in model.PassthroughMethods)
            WritePassthrough(sb, method);

        sb.AppendLine("}");
    }

    private static void WriteMethod(StringBuilder sb, MethodModel method)
    {
        var asyncKw = method.IsAsync ? "async " : "";
        sb.AppendLine($"    public {asyncKw}{method.ReturnTypeFqn} {method.Name}({method.ParameterList})");
        sb.AppendLine("    {");

        // 1. Rate limit
        if (method.RateLimit is not null)
        {
            sb.AppendLine("        if (!_rateLimiter.TryAcquire())");
            if (method.ReturnsFailureResult)
                sb.AppendLine($"            return {FailureExpression(method, "\"RateLimit\"", "\"Rate limit exceeded.\"", exceptionExpr: null)};");
            else
                sb.AppendLine("            throw new global::ZeroAlloc.Resilience.ResilienceException(global::ZeroAlloc.Resilience.ResiliencePolicy.RateLimit, \"Rate limit exceeded.\");");
            sb.AppendLine();
        }

        // 2. Circuit breaker check
        if (method.CircuitBreaker is not null)
        {
            sb.AppendLine("        if (!_circuitBreaker.CanExecute())");
            sb.AppendLine("        {");
            if (method.FallbackMethodName is not null)
            {
                var awaitFb = method.IsAsync ? "await " : "";
                var configFb = method.IsAsync ? ".ConfigureAwait(false)" : "";
                var fallbackCall = $"{awaitFb}_inner.{method.FallbackMethodName}({method.ArgumentList}){configFb}";
                if (method.ReturnsValue)
                    sb.AppendLine($"            return {fallbackCall};");
                else
                {
                    sb.AppendLine($"            {fallbackCall};");
                    sb.AppendLine("            return;");
                }
            }
            else if (method.ReturnsFailureResult)
                sb.AppendLine($"            return {FailureExpression(method, "\"CircuitBreaker\"", "\"Circuit breaker is open.\"", exceptionExpr: null)};");
            else
                sb.AppendLine("            throw new global::ZeroAlloc.Resilience.ResilienceException(global::ZeroAlloc.Resilience.ResiliencePolicy.CircuitBreaker, \"Circuit breaker is open.\");");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // 3. Total timeout CTS
        bool hasTotalTimeout = method.Timeout is not null;
        if (hasTotalTimeout)
        {
            if (method.CancellationTokenParamName is not null)
                sb.AppendLine($"        using var __totalCts = global::System.Threading.CancellationTokenSource.CreateLinkedTokenSource({method.CancellationTokenParamName});");
            else
                sb.AppendLine("        using var __totalCts = new global::System.Threading.CancellationTokenSource();");
            sb.AppendLine($"        __totalCts.CancelAfter({method.Timeout!.TotalMs});");
            sb.AppendLine();
        }

        // 4. Retry loop or single call
        if (method.Retry is not null)
        {
            WriteRetryLoop(sb, method, hasTotalTimeout);
        }
        else
        {
            WriteSingleCall(sb, method, hasTotalTimeout);
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void WriteRetryLoop(StringBuilder sb, MethodModel method, bool hasTotalTimeout)
    {
        var retry = method.Retry!;
        var awaitKw = method.IsAsync ? "await " : "";
        var configKw = method.IsAsync ? ".ConfigureAwait(false)" : "";

        sb.AppendLine("        global::System.Exception? __lastEx = null;");
        sb.AppendLine($"        for (int __attempt = 0; __attempt < {retry.MaxAttempts}; __attempt++)");
        sb.AppendLine("        {");

        // Per-attempt timeout CTS
        if (retry.PerAttemptTimeoutMs > 0 && method.HasCancellationToken)
        {
            var innerToken = hasTotalTimeout ? "__totalCts.Token" : method.CancellationTokenParamName ?? "default";
            sb.AppendLine($"            using var __attemptCts = global::System.Threading.CancellationTokenSource.CreateLinkedTokenSource({innerToken});");
            sb.AppendLine($"            __attemptCts.CancelAfter({retry.PerAttemptTimeoutMs});");
            sb.AppendLine("            var __ct = __attemptCts.Token;");
        }
        else if (hasTotalTimeout)
        {
            sb.AppendLine("            var __ct = __totalCts.Token;");
        }
        else if (method.HasCancellationToken)
        {
            sb.AppendLine($"            var __ct = {method.CancellationTokenParamName ?? "default"};");
        }

        sb.AppendLine("            try");
        sb.AppendLine("            {");
        var callArgs = method.HasCancellationToken ? method.ArgumentListWithToken : method.ArgumentList;
        sb.AppendLine($"                {CaptureCall(method, $"{awaitKw}_inner.{method.Name}({callArgs}){configKw}")}");
        if (method.CircuitBreaker is not null)
            sb.AppendLine("                _circuitBreaker.OnSuccess();");
        sb.AppendLine($"                {ReturnCaptured(method)}");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (global::System.Exception __ex)");
        sb.AppendLine("            {");
        sb.AppendLine("                __lastEx = __ex;");
        if (method.CircuitBreaker is not null)
            sb.AppendLine("                _circuitBreaker.OnFailure(__ex);");
        if (hasTotalTimeout)
            sb.AppendLine("                if (__totalCts.IsCancellationRequested) break;");
        sb.AppendLine($"                if (__attempt == {retry.MaxAttempts - 1}) break;");
        if (method.IsAsync)
        {
            var delayToken = hasTotalTimeout ? ", __totalCts.Token" : "";
            var backoffExpr = retry.Jitter
                ? $"{retry.BackoffMs} * (1 << __attempt) + global::System.Random.Shared.Next(0, global::System.Math.Max(1, {retry.BackoffMs} * (1 << __attempt) / 2))"
                : $"{retry.BackoffMs} * (1 << __attempt)";
            sb.AppendLine($"                await global::System.Threading.Tasks.Task.Delay({backoffExpr}{delayToken}).ConfigureAwait(false);");
        }
        else
        {
            var backoffExpr = retry.Jitter
                ? $"{retry.BackoffMs} * (1 << __attempt) + global::System.Random.Shared.Next(0, global::System.Math.Max(1, {retry.BackoffMs} * (1 << __attempt) / 2))"
                : $"{retry.BackoffMs} * (1 << __attempt)";
            sb.AppendLine($"                global::System.Threading.Thread.Sleep({backoffExpr});");
        }
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        // All attempts exhausted");
        if (method.Retry!.NonThrowing && method.ResultKind != ResultKind.ResilienceError)
        {
            // NonThrowing=true but type extraction failed — emit a hard compile error instead of silently generating throwing code
            sb.AppendLine($"#error ZR: [Retry(NonThrowing = true)] requires the method return type to be Result<T, ResilienceError> or UnitResult<ResilienceError> (on method '{method.Name}')");
        }
        else if (method.ReturnsFailureResult)
        {
            // Result return types get a failure of their own type instead of an exception.
            sb.AppendLine($"        return {FailureExpression(method, "\"Retry\"", "__lastEx?.Message ?? \"All retry attempts failed.\"", "__lastEx")};");
        }
        else
        {
            // Also Result<T, E> with a foreign E: every attempt threw, so there is no inner
            // Result to return and no way to build an E.
            sb.AppendLine("        throw new global::ZeroAlloc.Resilience.ResilienceException(global::ZeroAlloc.Resilience.ResiliencePolicy.Retry, \"All retry attempts failed.\", __lastEx);");
        }
    }

    private static void WriteSingleCall(StringBuilder sb, MethodModel method, bool hasTotalTimeout)
    {
        var awaitKw = method.IsAsync ? "await " : "";
        var configKw = method.IsAsync ? ".ConfigureAwait(false)" : "";

        string callArgs;
        if (hasTotalTimeout && method.HasCancellationToken)
        {
            // ArgumentListWithToken has __ct in place of the CT param — define __ct = __totalCts.Token
            sb.AppendLine("        var __ct = __totalCts.Token;");
            callArgs = method.ArgumentListWithToken;
        }
        else
        {
            callArgs = method.ArgumentList;
        }

        if (method.ReturnsFailureResult)
        {
            // The catch records the exception and the failure is built after it, the same
            // shape as retry exhaustion.
            sb.AppendLine("        global::System.Exception __lastEx;");
            sb.AppendLine("        try");
            sb.AppendLine("        {");
            sb.AppendLine($"            {CaptureCall(method, $"{awaitKw}_inner.{method.Name}({callArgs}){configKw}")}");
            if (method.CircuitBreaker is not null)
                sb.AppendLine("            _circuitBreaker.OnSuccess();");
            sb.AppendLine($"            {ReturnCaptured(method)}");
            sb.AppendLine("        }");
            sb.AppendLine("        catch (global::System.Exception __ex)");
            sb.AppendLine("        {");
            sb.AppendLine("            __lastEx = __ex;");
            if (method.CircuitBreaker is not null)
                sb.AppendLine("            _circuitBreaker.OnFailure(__ex);");
            sb.AppendLine("        }");
            sb.AppendLine($"        return {FailureExpression(method, SingleCallPolicyExpression(method, hasTotalTimeout), "__lastEx.Message", "__lastEx")};");
        }
        else if (method.CircuitBreaker is not null)
        {
            sb.AppendLine("        try");
            sb.AppendLine("        {");
            sb.AppendLine($"            {CaptureCall(method, $"{awaitKw}_inner.{method.Name}({callArgs}){configKw}")}");
            sb.AppendLine("            _circuitBreaker.OnSuccess();");
            sb.AppendLine($"            {ReturnCaptured(method)}");
            sb.AppendLine("        }");
            sb.AppendLine("        catch (global::System.Exception __ex)");
            sb.AppendLine("        {");
            sb.AppendLine("            _circuitBreaker.OnFailure(__ex);");
            sb.AppendLine("            throw;");
            sb.AppendLine("        }");
        }
        else
        {
            var call = $"{awaitKw}_inner.{method.Name}({callArgs}){configKw}";
            sb.AppendLine(method.ReturnsValue ? $"        return {call};" : $"        {call};");
        }
    }

    // The inner call as a statement: captured in __result when the method returns a value, a bare
    // statement for void, ValueTask and Task.
    private static string CaptureCall(MethodModel method, string call) =>
        method.ReturnsValue ? $"var __result = {call};" : $"{call};";

    private static string ReturnCaptured(MethodModel method) =>
        method.ReturnsValue ? "return __result;" : "return;";

    // A failure of the method's own Result type. Only valid when ReturnsFailureResult holds; a
    // foreign error type never reaches here.
    private static string FailureExpression(MethodModel method, string policyExpr, string messageExpr, string? exceptionExpr)
    {
        if (method.ResultKind == ResultKind.ResilienceError)
        {
            var exceptionArg = exceptionExpr is null ? "" : $", {exceptionExpr}";
            return $"{method.ResultTypeFqn}.Failure(new global::ZeroAlloc.Resilience.ResilienceError({policyExpr}, {messageExpr}{exceptionArg}))";
        }
        return $"{method.ResultTypeFqn}.Failure({messageExpr})";
    }

    // PolicyType of the ResilienceError for a single call that threw: Timeout when the total
    // timeout fired, otherwise the policy guarding the call.
    private static string SingleCallPolicyExpression(MethodModel method, bool hasTotalTimeout)
    {
        var guard = method.CircuitBreaker is not null ? "\"CircuitBreaker\""
            : hasTotalTimeout ? "\"Timeout\""
            : "\"RateLimit\"";
        return hasTotalTimeout && method.CircuitBreaker is not null
            ? $"__totalCts.IsCancellationRequested ? \"Timeout\" : {guard}"
            : guard;
    }

    private static void WritePassthrough(StringBuilder sb, PassthroughMethodModel method)
    {
        var awaitKw = method.IsAsync ? "await " : "";
        var configKw = method.IsAsync ? ".ConfigureAwait(false)" : "";
        var asyncKw = method.IsAsync ? "async " : "";
        sb.AppendLine($"    public {asyncKw}{method.ReturnTypeFqn} {method.Name}({method.ParameterList})");
        sb.AppendLine($"        => {awaitKw}_inner.{method.Name}({method.ArgumentList}){configKw};");
        sb.AppendLine();
    }

    private static void WriteDiExtension(StringBuilder sb, ResilienceModel model)
    {
        var hasRetry   = model.Methods.Any(static m => m.Retry is not null);
        var hasTimeout = model.Methods.Any(static m => m.Timeout is not null);
        var hasRate    = model.Methods.Any(static m => m.RateLimit is not null);
        var hasCb      = model.Methods.Any(static m => m.CircuitBreaker is not null);

        var retry   = model.ClassRetry   ?? model.Methods.FirstOrDefault(static m => m.Retry is not null)?.Retry;
        var timeout = model.ClassTimeout ?? model.Methods.FirstOrDefault(static m => m.Timeout is not null)?.Timeout;
        var rate    = model.ClassRateLimit ?? model.Methods.FirstOrDefault(static m => m.RateLimit is not null)?.RateLimit;
        var cb      = model.ClassCircuitBreaker ?? model.Methods.FirstOrDefault(static m => m.CircuitBreaker is not null)?.CircuitBreaker;

        // Partial declarations must agree on accessibility, so non-public interfaces get their
        // own internal class instead of sharing the public ResilienceServiceCollectionExtensions.
        sb.AppendLine(model.IsPublic
            ? "public static partial class ResilienceServiceCollectionExtensions"
            : "internal static partial class InternalResilienceServiceCollectionExtensions");
        sb.AppendLine("{");
        sb.AppendLine($"    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection Add{model.InterfaceName.TrimStart('I')}Resilience<");
        // IL2091: TImpl flows into AddTransient<T> which requires PublicConstructors.
        sb.AppendLine("        [global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(");
        sb.AppendLine("            global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)]");
        sb.AppendLine("        TImpl>(");
        sb.AppendLine($"        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine($"        where TImpl : class, {model.InterfaceFqn}");
        sb.AppendLine("    {");
        sb.AppendLine("        services.AddTransient<TImpl>();");

        if (hasRetry && retry is not null)
            sb.AppendLine($"        services.AddSingleton(new global::ZeroAlloc.Resilience.RetryPolicy({retry.MaxAttempts}, {retry.BackoffMs}, {(retry.Jitter ? "true" : "false")}, {retry.PerAttemptTimeoutMs}));");
        if (hasTimeout && timeout is not null)
            sb.AppendLine($"        services.AddSingleton(new global::ZeroAlloc.Resilience.TimeoutPolicy({timeout.TotalMs}));");
        if (hasRate && rate is not null)
            sb.AppendLine($"        services.AddSingleton(new global::ZeroAlloc.Resilience.RateLimiter({rate.MaxPerSecond}, {rate.BurstSize}, global::ZeroAlloc.Resilience.RateLimitScope.{rate.Scope}));");
        if (hasCb && cb is not null)
            sb.AppendLine($"        services.AddSingleton(new global::ZeroAlloc.Resilience.CircuitBreakerPolicy({cb.MaxFailures}, {cb.ResetMs}, {cb.HalfOpenProbes}));");

        sb.Append($"        services.AddTransient<{model.InterfaceFqn}>(sp => new {model.InterfaceName}ResilienceProxy(");
        sb.Append("sp.GetRequiredService<TImpl>()");
        if (hasRetry)   sb.Append(", sp.GetRequiredService<global::ZeroAlloc.Resilience.RetryPolicy>()");
        if (hasTimeout) sb.Append(", sp.GetRequiredService<global::ZeroAlloc.Resilience.TimeoutPolicy>()");
        if (hasRate)    sb.Append(", sp.GetRequiredService<global::ZeroAlloc.Resilience.RateLimiter>()");
        if (hasCb)      sb.Append(", sp.GetRequiredService<global::ZeroAlloc.Resilience.CircuitBreakerPolicy>()");
        sb.AppendLine("));");

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

}
