namespace ZeroAlloc.Resilience.Generator;

using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;

internal static class ResilienceWriter
{
    public static string Write(ResilienceModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using ZeroAlloc.Resilience;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();

        if (model.Namespace is not null)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        WritePolicies(sb, model);
        sb.AppendLine();
        WriteProxy(sb, model);
        sb.AppendLine();
        WriteDiExtension(sb, model);

        return sb.ToString();
    }

    // One settable property per slot, defaulting to the attribute values, so a new instance is a
    // complete configuration. Its accessibility follows EmitPublicEntryPoints, like the DI
    // extension: public for a public interface unless ZeroAllocGeneratedAccessibility=Internal
    // forces it internal (#152).
    private static void WritePolicies(StringBuilder sb, ResilienceModel model)
    {
        sb.AppendLine($"{(model.EmitPublicEntryPoints ? "public" : "internal")} sealed class {model.PoliciesClassName}");
        sb.AppendLine("{");
        foreach (var slot in model.Slots)
            sb.AppendLine($"    public {slot.TypeFqn} {slot.PropertyName} {{ get; set; }} = {slot.DefaultExpression};");
        sb.AppendLine("}");
    }

    private static void WriteProxy(StringBuilder sb, ResilienceModel model)
    {
        // Only the slots some method reads become fields; an interface slot that every method
        // overrides stays on the policies class but is not copied.
        var used = model.Slots.Where(s => model.Methods.Any(m =>
            m.RetrySlot == s || m.TimeoutSlot == s || m.RateLimiterSlot == s || m.CircuitBreakerSlot == s)).ToImmutableArray();

        sb.AppendLine($"internal sealed class {model.InterfaceName}ResilienceProxy : {model.InterfaceFqn}");
        sb.AppendLine("{");
        sb.AppendLine($"    private readonly {model.InterfaceFqn} _inner;");
        foreach (var slot in used)
            sb.AppendLine($"    private readonly {slot.TypeFqn} {slot.FieldName};");
        sb.AppendLine();

        // The constructor copies each slot, so changing the policies afterwards only affects
        // proxies created later.
        sb.AppendLine($"    public {model.InterfaceName}ResilienceProxy({model.InterfaceFqn} inner, {model.PoliciesClassName} policies)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(inner);");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(policies);");
        sb.AppendLine("        _inner = inner;");
        foreach (var slot in used)
        {
            var read = $"(policies.{slot.PropertyName} ?? throw new global::System.ArgumentException(\"{model.PoliciesClassName}.{slot.PropertyName} is null.\", nameof(policies)))";
            sb.AppendLine(slot.Kind == PolicyKind.RateLimiter
                ? $"        {slot.FieldName} = {read}.ForProxyInstance();"
                : $"        {slot.FieldName} = {read};");
        }
        sb.AppendLine("    }");
        sb.AppendLine();

        foreach (var method in model.Methods)
            WriteMethod(sb, method);

        foreach (var method in model.PassthroughMethods)
            WritePassthrough(sb, method);

        foreach (var member in model.PassthroughMembers)
            WritePassthroughMember(sb, member);

        sb.AppendLine("}");
    }

    private static void WriteMethod(StringBuilder sb, MethodModel method)
    {
        var asyncKw = method.IsAsync ? "async " : "";
        if (method.ExplicitImplementations.Length == 0)
        {
            sb.AppendLine(MethodHeader(method.ExplicitInterface, method.HidesObjectMember, asyncKw, method.ReturnTypeFqn, method.Name,
                method.TypeParameterList, method.ParameterList, method.ConstraintClauses, method.ExplicitConstraintClauses));
            WriteMethodBody(sb, method);
            return;
        }

        // Collapsed declarations: the public member and one explicit implementation per other
        // declaration all run one policy-wrapped body, which takes the index of the declaration
        // to call on the inner service. The policies, and so the slots, are shared.
        var core = $"__{method.HelperName}_Resilient{method.TypeParameterList}";
        var args = method.ArgumentList.Length == 0 ? "" : ", " + method.ArgumentList;
        var declarations = method.ExplicitImplementations.Split('|');
        sb.AppendLine(MethodHeader(method.ExplicitInterface, method.HidesObjectMember, "", method.ReturnTypeFqn, method.Name,
            method.TypeParameterList, method.ParameterList, method.ConstraintClauses, method.ExplicitConstraintClauses));
        sb.AppendLine($"        => {core}(0{args});");
        sb.AppendLine();
        for (var i = 0; i < declarations.Length; i++)
        {
            sb.AppendLine($"    {method.ReturnTypeFqn} {declarations[i]}.{method.Name}{method.TypeParameterList}({method.ParameterList}){method.ExplicitConstraintClauses}");
            sb.AppendLine($"        => {core}({(i + 1).ToString(CultureInfo.InvariantCulture)}{args});");
            sb.AppendLine();
        }

        var parameters = method.ParameterList.Length == 0 ? "" : ", " + method.ParameterList;
        sb.AppendLine($"    private {asyncKw}{method.ReturnTypeFqn} __{method.HelperName}_Resilient{method.TypeParameterList}(int __declaration{parameters}){method.ConstraintClauses}");
        WriteMethodBody(sb, method);

        // The inner call for one declaration, through that declaration's own interface.
        sb.AppendLine($"    private {method.ReturnTypeFqn} __{method.HelperName}_Inner{method.TypeParameterList}(int __declaration{parameters}){method.ConstraintClauses}");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (__declaration)");
        sb.AppendLine("        {");
        for (var i = 0; i < declarations.Length; i++)
        {
            sb.AppendLine($"            case {(i + 1).ToString(CultureInfo.InvariantCulture)}:");
            WriteDispatchCall(sb, method, $"(({declarations[i]})_inner)");
        }
        sb.AppendLine("            default:");
        WriteDispatchCall(sb, method, method.InnerReceiver);
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void WriteDispatchCall(StringBuilder sb, MethodModel method, string receiver)
    {
        var call = $"{receiver}.{method.Name}{method.TypeParameterList}({method.ArgumentList})";
        if (string.Equals(method.ReturnTypeFqn, "void", System.StringComparison.Ordinal))
        {
            sb.AppendLine($"                {call};");
            sb.AppendLine("                return;");
        }
        else
        {
            sb.AppendLine($"                return {call};");
        }
    }

    // The inner call with the given arguments: on the declaration's receiver, or through the
    // dispatch method of a collapsed member.
    private static string InnerCall(MethodModel method, string args) =>
        method.ExplicitImplementations.Length == 0
            ? $"{method.InnerReceiver}.{method.Name}{method.TypeParameterList}({args})"
            : $"__{method.HelperName}_Inner{method.TypeParameterList}(__declaration{(args.Length == 0 ? "" : ", " + args)})";

    // "public async T Name<T>(...) where ..." for a public member; "async T global::Ns.IBase.Name<T>(...)"
    // for an explicit implementation, which states only the `class` or `default` constraints `T?` needs.
    // A public member that hides an object member by name and parameters gets `new`.
    private static string MethodHeader(string explicitInterface, bool hidesObjectMember, string asyncKw, string returnType, string name,
        string typeParameters, string parameters, string constraints, string explicitConstraints) =>
        explicitInterface.Length == 0
            ? $"    public {(hidesObjectMember ? "new " : "")}{asyncKw}{returnType} {name}{typeParameters}({parameters}){constraints}"
            : $"    {asyncKw}{returnType} {explicitInterface}.{name}{typeParameters}({parameters}){explicitConstraints}";

    private static void WriteMethodBody(StringBuilder sb, MethodModel method)
    {
        sb.AppendLine("    {");

        // 0. out parameters: every path that returns without a successful inner call, a failure
        // Result or a fallback that throws, still has to assign them.
        if (method.OutParameterNames.Length > 0)
        {
            foreach (var name in method.OutParameterNames.Split(','))
                sb.AppendLine($"        {name} = default!;");
            sb.AppendLine();
        }

        // 1. Rate limit
        if (method.RateLimit is not null)
        {
            sb.AppendLine($"        if (!{method.RateLimiterSlot!.FieldName}.TryAcquire())");
            if (method.ReturnsFailureResult)
                sb.AppendLine($"            return {FailureExpression(method, "\"RateLimit\"", "\"Rate limit exceeded.\"", exceptionExpr: null)};");
            else
                sb.AppendLine("            throw new global::ZeroAlloc.Resilience.ResilienceException(global::ZeroAlloc.Resilience.ResiliencePolicy.RateLimit, \"Rate limit exceeded.\");");
            sb.AppendLine();
        }

        // 2. Circuit breaker check
        if (method.CircuitBreaker is not null)
        {
            sb.AppendLine($"        if (!{method.CircuitBreakerSlot!.FieldName}.CanExecute())");
            sb.AppendLine("        {");
            if (method.FallbackMethodName is not null)
            {
                var awaitFb = method.IsAsync ? "await " : "";
                var configFb = method.IsAsync ? ".ConfigureAwait(false)" : "";
                var fallbackCall = $"{awaitFb}{method.FallbackReceiver}.{method.FallbackMethodName}({method.ArgumentList}){configFb}";
                if (method.ReturnsValue)
                    sb.AppendLine($"            return {fallbackCall};");
                else
                {
                    sb.AppendLine($"            {fallbackCall};");
                    sb.AppendLine("            return;");
                }
            }
            else if (method.ReturnsFailureResult)
                sb.AppendLine($"            return {FailureExpression(method, "\"CircuitBreaker\"", "\"Circuit breaker is open.\"", exceptionExpr: null)};");
            else
                sb.AppendLine("            throw new global::ZeroAlloc.Resilience.ResilienceException(global::ZeroAlloc.Resilience.ResiliencePolicy.CircuitBreaker, \"Circuit breaker is open.\");");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // 3. Total timeout CTS
        bool hasTotalTimeout = method.Timeout is not null;
        if (hasTotalTimeout)
        {
            if (method.CancellationTokenParamName is not null)
                sb.AppendLine($"        using var __totalCts = global::System.Threading.CancellationTokenSource.CreateLinkedTokenSource({method.CancellationTokenParamName});");
            else
                sb.AppendLine("        using var __totalCts = new global::System.Threading.CancellationTokenSource();");
            sb.AppendLine($"        __totalCts.CancelAfter({method.TimeoutSlot!.FieldName}.TotalMs);");
            sb.AppendLine();
        }

        // 4. Retry loop or single call
        if (method.Retry is not null)
        {
            if (method.RetryWhenMethod is not null)
                WriteResultAwareRetryLoop(sb, method, hasTotalTimeout);
            else
                WriteRetryLoop(sb, method, hasTotalTimeout);
        }
        else
        {
            WriteSingleCall(sb, method, hasTotalTimeout);
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void WriteRetryLoop(StringBuilder sb, MethodModel method, bool hasTotalTimeout)
    {
        var retry = method.RetrySlot!.FieldName;
        var awaitKw = method.IsAsync ? "await " : "";
        var configKw = method.IsAsync ? ".ConfigureAwait(false)" : "";

        sb.AppendLine("        global::System.Exception? __lastEx = null;");
        sb.AppendLine($"        for (int __attempt = 0; __attempt < {retry}.MaxAttempts; __attempt++)");
        sb.AppendLine("        {");
        WriteAttemptToken(sb, method, retry, hasTotalTimeout);
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        var callArgs = method.HasCancellationToken ? method.ArgumentListWithToken : method.ArgumentList;
        sb.AppendLine($"                {CaptureCall(method, $"{awaitKw}{InnerCall(method, callArgs)}{configKw}")}");
        if (method.CircuitBreaker is not null)
            sb.AppendLine($"                {method.CircuitBreakerSlot!.FieldName}.OnSuccess();");
        sb.AppendLine($"                {ReturnCaptured(method)}");
        sb.AppendLine("            }");
        WriteCallerCancellationCatch(sb, method);
        sb.AppendLine("            catch (global::System.Exception __ex)");
        sb.AppendLine("            {");
        sb.AppendLine("                __lastEx = __ex;");
        if (method.CircuitBreaker is not null)
            sb.AppendLine($"                {method.CircuitBreakerSlot!.FieldName}.OnFailure(__ex);");
        // RetryOnException and the Exception overload of DelayHint run in the catch block, which
        // is outside the try it guards: an exception they throw reaches the caller unchanged.
        if (method.RetryOnExceptionMethod is not null)
            sb.AppendLine($"                if (!{method.RetryOnExceptionMethod}(__ex)) break;");
        var delay = $"{retry}.GetBackoffMs(__attempt)";
        if (method.ExceptionDelayHintMethod is not null)
        {
            sb.AppendLine($"                var __hint = {method.ExceptionDelayHintMethod}(__ex);");
            delay = $"{retry}.GetDelayMs(__attempt, __hint)";
        }
        if (hasTotalTimeout)
            WriteTotalTimeoutExit(sb, method, "                ");
        sb.AppendLine($"                if (__attempt == {retry}.MaxAttempts - 1) break;");
        WriteBackoffWait(sb, method, hasTotalTimeout, delay, "                ");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        // All attempts exhausted");
        WriteRetryExhaustion(sb, method);
    }

    // Every attempt threw, or RetryOnException declined the last exception.
    private static void WriteRetryExhaustion(StringBuilder sb, MethodModel method)
    {
        // NonThrowing on a return type that cannot hold a ResilienceError never reaches the writer:
        // it is ZR0003, or ZR0006 with NonThrowing left off an inherited default method.
        if (method.ReturnsFailureResult)
        {
            // Result return types get a failure of their own type instead of an exception.
            sb.AppendLine($"        return {FailureExpression(method, "\"Retry\"", "__lastEx?.Message ?? \"All retry attempts failed.\"", "__lastEx")};");
        }
        else
        {
            // Also Result<T, E> with a foreign E: every attempt threw, so there is no inner
            // Result to return and no way to build an E.
            sb.AppendLine("        throw new global::ZeroAlloc.Resilience.ResilienceException(global::ZeroAlloc.Resilience.ResiliencePolicy.Retry, \"All retry attempts failed.\", __lastEx);");
        }
    }

    // [Retry] with a RetryWhen that applies to this Result method. Only the inner call is inside
    // the try; RetryWhen and the Result DelayHint run after it, and RetryOnException and the
    // Exception DelayHint in the catch block, so an exception any of them throws reaches the
    // caller unchanged. A failed Result RetryWhen calls transient is a breaker failure and is
    // retried; any other returned Result is a breaker success and is returned. When the retries
    // end on a failed Result, including when the total timeout fires during the wait after it,
    // that Result is returned unchanged; the caller's own cancellation still throws.
    private static void WriteResultAwareRetryLoop(StringBuilder sb, MethodModel method, bool hasTotalTimeout)
    {
        var retry = method.RetrySlot!.FieldName;
        var awaitKw = method.IsAsync ? "await " : "";
        var configKw = method.IsAsync ? ".ConfigureAwait(false)" : "";
        var breaker = method.CircuitBreaker is null ? null : method.CircuitBreakerSlot!.FieldName;
        var hasHint = method.ResultDelayHintMethod is not null || method.ExceptionDelayHintMethod is not null;

        sb.AppendLine("        global::System.Exception? __lastEx = null;");
        sb.AppendLine($"        {method.ResultTypeFqn} __lastResult = default;");
        sb.AppendLine("        bool __lastWasResult = false;");
        sb.AppendLine($"        for (int __attempt = 0; __attempt < {retry}.MaxAttempts; __attempt++)");
        sb.AppendLine("        {");
        WriteAttemptToken(sb, method, retry, hasTotalTimeout);
        if (hasHint)
            sb.AppendLine("            global::System.TimeSpan? __hint = null;");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        var callArgs = method.HasCancellationToken ? method.ArgumentListWithToken : method.ArgumentList;
        sb.AppendLine($"                __lastResult = {awaitKw}{InnerCall(method, callArgs)}{configKw};");
        sb.AppendLine("                __lastWasResult = true;");
        sb.AppendLine("            }");
        WriteCallerCancellationCatch(sb, method);
        sb.AppendLine("            catch (global::System.Exception __ex)");
        sb.AppendLine("            {");
        sb.AppendLine("                __lastEx = __ex;");
        sb.AppendLine("                __lastWasResult = false;");
        if (breaker is not null)
            sb.AppendLine($"                {breaker}.OnFailure(__ex);");
        if (method.RetryOnExceptionMethod is not null)
            sb.AppendLine($"                if (!{method.RetryOnExceptionMethod}(__ex)) break;");
        if (method.ExceptionDelayHintMethod is not null)
            sb.AppendLine($"                __hint = {method.ExceptionDelayHintMethod}(__ex);");
        sb.AppendLine("            }");
        sb.AppendLine("            if (__lastWasResult)");
        sb.AppendLine("            {");
        sb.AppendLine($"                if (__lastResult.IsSuccess || !{method.RetryWhenMethod}(__lastResult.Error))");
        sb.AppendLine("                {");
        if (breaker is not null)
            sb.AppendLine($"                    {breaker}.OnSuccess();");
        sb.AppendLine("                    return __lastResult;");
        sb.AppendLine("                }");
        if (breaker is not null)
            sb.AppendLine($"                {breaker}.OnFailure();");
        if (method.ResultDelayHintMethod is not null)
            sb.AppendLine($"                __hint = {method.ResultDelayHintMethod}(__lastResult.Error);");
        sb.AppendLine("            }");
        if (hasTotalTimeout)
            WriteTotalTimeoutExit(sb, method, "            ");
        sb.AppendLine($"            if (__attempt == {retry}.MaxAttempts - 1) break;");
        var delay = hasHint ? $"{retry}.GetDelayMs(__attempt, __hint)" : $"{retry}.GetBackoffMs(__attempt)";
        WriteBackoffWait(sb, method, hasTotalTimeout, delay, "            ");
        sb.AppendLine("        }");
        sb.AppendLine("        // All attempts exhausted, or a failure that is not retried");
        sb.AppendLine("        if (__lastWasResult) return __lastResult;");
        WriteRetryExhaustion(sb, method);
    }

    // The per-attempt timeout is a runtime value, so the CTS is created only when it is set.
    // Without a CancellationToken parameter there is nothing to propagate it to; ZR0002 warns
    // when the attribute asks for one.
    private static void WriteAttemptToken(StringBuilder sb, MethodModel method, string retry, bool hasTotalTimeout)
    {
        if (method.HasCancellationToken)
        {
            var outerToken = hasTotalTimeout ? "__totalCts.Token" : method.CancellationTokenParamName!;
            sb.AppendLine($"            using var __attemptCts = {retry}.PerAttemptTimeoutMs > 0");
            sb.AppendLine($"                ? global::System.Threading.CancellationTokenSource.CreateLinkedTokenSource({outerToken})");
            sb.AppendLine("                : null;");
            sb.AppendLine($"            __attemptCts?.CancelAfter({retry}.PerAttemptTimeoutMs);");
            sb.AppendLine($"            var __ct = __attemptCts?.Token ?? {outerToken};");
        }
        else if (hasTotalTimeout)
        {
            sb.AppendLine("            var __ct = __totalCts.Token;");
        }
    }

    // The caller's own cancellation is not a failure of the inner call. Caught before the catch
    // that retries, it is rethrown unchanged: not retried, not counted by the circuit breaker and
    // not wrapped in ResilienceException. A per-attempt or total timeout leaves the caller's token
    // untouched, so its OperationCanceledException still reaches the retrying catch.
    // The single-call path uses it too, at its own indent.
    private static void WriteCallerCancellationCatch(StringBuilder sb, MethodModel method, string indent = "            ")
    {
        if (method.CancellationTokenParamName is not { } callerToken) return;
        sb.AppendLine($"{indent}catch (global::System.OperationCanceledException) when ({callerToken}.IsCancellationRequested)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    throw;");
        sb.AppendLine($"{indent}}}");
    }

    // Ends the loop when the total-timeout token has fired. That token is linked to the caller's,
    // so a cancelled caller throws OperationCanceledException first, exactly as the loop without
    // [Timeout] does. Only the timeout itself ends the loop: the exception-only loop then exits
    // through exhaustion, and the Result-aware loop returns its last Result.
    private static void WriteTotalTimeoutExit(StringBuilder sb, MethodModel method, string indent)
    {
        if (method.CancellationTokenParamName is null)
        {
            sb.AppendLine($"{indent}if (__totalCts.IsCancellationRequested) break;");
            return;
        }

        sb.AppendLine($"{indent}if (__totalCts.IsCancellationRequested)");
        WriteTotalTimeoutBlock(sb, method, indent);
    }

    // The body that follows a check that the total-timeout token fired.
    private static void WriteTotalTimeoutBlock(StringBuilder sb, MethodModel method, string indent)
    {
        sb.AppendLine($"{indent}{{");
        if (method.CancellationTokenParamName is { } callerToken)
            sb.AppendLine($"{indent}    {callerToken}.ThrowIfCancellationRequested();");
        sb.AppendLine($"{indent}    break;");
        sb.AppendLine($"{indent}}}");
    }

    // The wait before the next attempt. It observes the total-timeout token when [Timeout] is
    // present, and the caller's token otherwise. With [Timeout], the total-timeout token is linked
    // to the caller's, so either can end the wait: a cancelled caller throws
    // OperationCanceledException and a fired total timeout ends the loop, never with the wait's own
    // TaskCanceledException: the exception-only loop then exits through exhaustion, a Failure or a
    // ResilienceException, and the Result-aware loop returns its last Result. Async awaits
    // the delay with SuppressThrowing and then checks which one fired. Sync waits on the token's
    // wait handle, so cancellation interrupts the wait, which Thread.Sleep would not. Without
    // [Timeout], async Task.Delay throws when the caller's token fires, and Thread.Sleep remains
    // only when no token can be cancelled.
    private static void WriteBackoffWait(StringBuilder sb, MethodModel method, bool hasTotalTimeout, string delayExpr, string indent)
    {
        var callerToken = method.CancellationTokenParamName;
        if (method.IsAsync && !hasTotalTimeout)
        {
            var tokenArg = callerToken is not null ? $", {callerToken}" : "";
            sb.AppendLine($"{indent}await global::System.Threading.Tasks.Task.Delay({delayExpr}{tokenArg}).ConfigureAwait(false);");
            return;
        }

        if (hasTotalTimeout)
        {
            if (method.IsAsync)
            {
                // ConfigureAwaitOptions is .NET 8 and later, as is every target of the runtime.
                sb.AppendLine($"{indent}await global::System.Threading.Tasks.Task.Delay({delayExpr}, __totalCts.Token)");
                sb.AppendLine($"{indent}    .ConfigureAwait(global::System.Threading.Tasks.ConfigureAwaitOptions.SuppressThrowing);");
                sb.AppendLine($"{indent}if (__totalCts.IsCancellationRequested)");
            }
            else
            {
                sb.AppendLine($"{indent}if (__totalCts.Token.WaitHandle.WaitOne({delayExpr}))");
            }
            WriteTotalTimeoutBlock(sb, method, indent);
            return;
        }

        if (callerToken is not null)
        {
            // CanBeCanceled: a token that can never fire has no wait handle worth creating.
            sb.AppendLine($"{indent}if ({callerToken}.CanBeCanceled)");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    {callerToken}.WaitHandle.WaitOne({delayExpr});");
            sb.AppendLine($"{indent}    {callerToken}.ThrowIfCancellationRequested();");
            sb.AppendLine($"{indent}}}");
            sb.AppendLine($"{indent}else");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    global::System.Threading.Thread.Sleep({delayExpr});");
            sb.AppendLine($"{indent}}}");
            return;
        }

        sb.AppendLine($"{indent}global::System.Threading.Thread.Sleep({delayExpr});");
    }

    // A catch here, for a Result method or a circuit breaker, first rethrows the caller's own
    // cancellation, as the retry loop does: it is not a Failure and not a breaker failure.
    private static void WriteSingleCall(StringBuilder sb, MethodModel method, bool hasTotalTimeout)
    {
        var awaitKw = method.IsAsync ? "await " : "";
        var configKw = method.IsAsync ? ".ConfigureAwait(false)" : "";

        string callArgs;
        if (hasTotalTimeout && method.HasCancellationToken)
        {
            // ArgumentListWithToken has __ct in place of the CT param — define __ct = __totalCts.Token
            sb.AppendLine("        var __ct = __totalCts.Token;");
            callArgs = method.ArgumentListWithToken;
        }
        else
        {
            callArgs = method.ArgumentList;
        }

        if (method.ReturnsFailureResult)
        {
            // The catch records the exception and the failure is built after it, the same
            // shape as retry exhaustion.
            sb.AppendLine("        global::System.Exception __lastEx;");
            sb.AppendLine("        try");
            sb.AppendLine("        {");
            sb.AppendLine($"            {CaptureCall(method, $"{awaitKw}{InnerCall(method, callArgs)}{configKw}")}");
            if (method.CircuitBreaker is not null)
                sb.AppendLine($"            {method.CircuitBreakerSlot!.FieldName}.OnSuccess();");
            sb.AppendLine($"            {ReturnCaptured(method)}");
            sb.AppendLine("        }");
            WriteCallerCancellationCatch(sb, method, "        ");
            sb.AppendLine("        catch (global::System.Exception __ex)");
            sb.AppendLine("        {");
            sb.AppendLine("            __lastEx = __ex;");
            if (method.CircuitBreaker is not null)
                sb.AppendLine($"            {method.CircuitBreakerSlot!.FieldName}.OnFailure(__ex);");
            sb.AppendLine("        }");
            sb.AppendLine($"        return {FailureExpression(method, SingleCallPolicyExpression(method, hasTotalTimeout), "__lastEx.Message", "__lastEx")};");
        }
        else if (method.CircuitBreaker is not null)
        {
            sb.AppendLine("        try");
            sb.AppendLine("        {");
            sb.AppendLine($"            {CaptureCall(method, $"{awaitKw}{InnerCall(method, callArgs)}{configKw}")}");
            sb.AppendLine($"            {method.CircuitBreakerSlot!.FieldName}.OnSuccess();");
            sb.AppendLine($"            {ReturnCaptured(method)}");
            sb.AppendLine("        }");
            WriteCallerCancellationCatch(sb, method, "        ");
            sb.AppendLine("        catch (global::System.Exception __ex)");
            sb.AppendLine("        {");
            sb.AppendLine($"            {method.CircuitBreakerSlot!.FieldName}.OnFailure(__ex);");
            sb.AppendLine("            throw;");
            sb.AppendLine("        }");
        }
        else
        {
            var call = $"{awaitKw}{InnerCall(method, callArgs)}{configKw}";
            sb.AppendLine(method.ReturnsValue ? $"        return {call};" : $"        {call};");
        }
    }

    // The inner call as a statement: captured in __result when the method returns a value, a bare
    // statement for void, ValueTask and Task.
    private static string CaptureCall(MethodModel method, string call) =>
        method.ReturnsValue ? $"var __result = {call};" : $"{call};";

    private static string ReturnCaptured(MethodModel method) =>
        method.ReturnsValue ? "return __result;" : "return;";

    // A failure of the method's own Result type. Only valid when ReturnsFailureResult holds; a
    // foreign error type never reaches here.
    private static string FailureExpression(MethodModel method, string policyExpr, string messageExpr, string? exceptionExpr)
    {
        if (method.ResultKind == ResultKind.ResilienceError)
        {
            var exceptionArg = exceptionExpr is null ? "" : $", {exceptionExpr}";
            return $"{method.ResultTypeFqn}.Failure(new global::ZeroAlloc.Resilience.ResilienceError({policyExpr}, {messageExpr}{exceptionArg}))";
        }
        return $"{method.ResultTypeFqn}.Failure({messageExpr})";
    }

    // PolicyType of the ResilienceError for a single call that threw: Timeout when the total
    // timeout fired, otherwise the policy guarding the call.
    private static string SingleCallPolicyExpression(MethodModel method, bool hasTotalTimeout)
    {
        var guard = method.CircuitBreaker is not null ? "\"CircuitBreaker\""
            : hasTotalTimeout ? "\"Timeout\""
            : "\"RateLimit\"";
        return hasTotalTimeout && method.CircuitBreaker is not null
            ? $"__totalCts.IsCancellationRequested ? \"Timeout\" : {guard}"
            : guard;
    }

    private static void WritePassthrough(StringBuilder sb, PassthroughMethodModel method)
    {
        var awaitKw = method.IsAsync ? "await " : "";
        var configKw = method.IsAsync ? ".ConfigureAwait(false)" : "";
        var asyncKw = method.IsAsync ? "async " : "";
        // A by-reference return forwards the inner reference: `=> ref _inner.Slot()`.
        var refKw = method.ReturnsByRef ? "ref " : "";
        sb.AppendLine(MethodHeader(method.ExplicitInterface, method.HidesObjectMember, asyncKw, method.ReturnTypeFqn, method.Name,
            method.TypeParameterList, method.ParameterList, method.ConstraintClauses, method.ExplicitConstraintClauses));
        sb.AppendLine($"        => {awaitKw}{refKw}{method.InnerReceiver}.{method.Name}{method.TypeParameterList}({method.ArgumentList}){configKw};");
        sb.AppendLine();

        // Collapsed declarations: each other declaration forwards through its own interface.
        foreach (var declaration in ExplicitDeclarations(method.ExplicitImplementations))
        {
            sb.AppendLine($"    {asyncKw}{method.ReturnTypeFqn} {declaration}.{method.Name}{method.TypeParameterList}({method.ParameterList}){method.ExplicitConstraintClauses}");
            sb.AppendLine($"        => {awaitKw}{refKw}(({declaration})_inner).{method.Name}{method.TypeParameterList}({method.ArgumentList}){configKw};");
            sb.AppendLine();
        }
    }

    private static string[] ExplicitDeclarations(string explicitImplementations) =>
        explicitImplementations.Length == 0 ? System.Array.Empty<string>() : explicitImplementations.Split('|');

    // No policy ever applies to a property, indexer or event — only methods carry [Retry],
    // [Timeout], [RateLimit] or [CircuitBreaker] — so every one of these is a plain forwarding
    // member, unchanged from the interface's own behaviour.
    private static void WritePassthroughMember(StringBuilder sb, PassthroughMemberModel member)
    {
        // The public member, then, for collapsed declarations, an explicit implementation for each
        // other declaration that forwards through its own interface.
        WritePassthroughMember(sb, member,
            member.ExplicitInterface.Length == 0 ? "public " : member.ExplicitInterface + ".", member.InnerReceiver);
        foreach (var declaration in ExplicitDeclarations(member.ExplicitImplementations))
            WritePassthroughMember(sb, member, $"{declaration}.", $"(({declaration})_inner)");
    }

    // prefix: "public " for the public member, "global::Ns.IBase." for an explicit implementation.
    private static void WritePassthroughMember(StringBuilder sb, PassthroughMemberModel member, string prefix, string receiver)
    {
        switch (member.Kind)
        {
            case PassthroughMemberKind.Property:
                WritePassthroughPropertyOrIndexer(sb, member, isIndexer: false, prefix, receiver);
                break;
            case PassthroughMemberKind.Indexer:
                WritePassthroughPropertyOrIndexer(sb, member, isIndexer: true, prefix, receiver);
                break;
            case PassthroughMemberKind.Event:
                WritePassthroughEvent(sb, member, prefix, receiver);
                break;
        }
    }

    private static void WritePassthroughPropertyOrIndexer(StringBuilder sb, PassthroughMemberModel member, bool isIndexer, string prefix, string receiver)
    {
        var isPublic = string.Equals(prefix, "public ", System.StringComparison.Ordinal);
        var header = (isPublic, isIndexer) switch
        {
            (true, true) => $"    public {member.TypeFqn} this[{member.ParameterList}]",
            (true, false) => $"    public {member.TypeFqn} {member.Name}",
            (false, true) => $"    {member.TypeFqn} {prefix}this[{member.ParameterList}]",
            (false, false) => $"    {member.TypeFqn} {prefix}{member.Name}",
        };
        // A by-reference property forwards the inner reference: `=> ref _inner.Slot`.
        var refKw = member.ReturnsByRef ? "ref " : "";
        var innerAccess = isIndexer
            ? $"{refKw}{receiver}[{member.ArgumentList}]"
            : $"{refKw}{receiver}.{member.Name}";

        // A get-only member with no setter or init accessor stays expression-bodied; anything
        // with a setter and/or an init accessor needs the block form so each accessor gets its
        // own line.
        if (member.HasGet && !member.HasSet && !member.HasInit)
        {
            sb.AppendLine($"{header} => {innerAccess};");
            sb.AppendLine();
            return;
        }

        sb.AppendLine(header);
        sb.AppendLine("    {");
        if (member.HasGet)
            sb.AppendLine($"        get => {innerAccess};");
        if (member.HasSet)
            sb.AppendLine($"        set => {innerAccess} = value;");
        if (member.HasInit)
        {
            // An init accessor can only be assigned inside an object-initializer expression, so
            // there is no method body that can forward a value to _inner's init accessor — by the
            // time this proxy's init accessor runs, _inner is already fully constructed and its
            // init-only member can no longer be assigned. Throwing tells the caller why, instead
            // of silently doing nothing.
            var memberDisplay = isIndexer ? "this[]" : member.Name;
            sb.AppendLine($"        init => throw new global::System.NotSupportedException(\"'{memberDisplay}' has an init-only accessor, which cannot be forwarded: an init accessor can only be assigned from an object initializer, and by the time this proxy's init accessor runs, the inner instance is already constructed.\");");
        }
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void WritePassthroughEvent(StringBuilder sb, PassthroughMemberModel member, string prefix, string receiver)
    {
        var header = string.Equals(prefix, "public ", System.StringComparison.Ordinal)
            ? $"    public event {member.TypeFqn} {member.Name}"
            : $"    event {member.TypeFqn} {prefix}{member.Name}";
        sb.AppendLine(header);
        sb.AppendLine("    {");
        sb.AppendLine($"        add => {receiver}.{member.Name} += value;");
        sb.AppendLine($"        remove => {receiver}.{member.Name} -= value;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void WriteDiExtension(StringBuilder sb, ResilienceModel model)
    {
        var name = ResilienceGenerator.ServiceName(model.InterfaceName);
        var policies = model.PoliciesClassName;

        // Partial declarations must agree on accessibility, so an interface whose entry points are
        // not emitted public — an internal interface (#146), or a public one with
        // ZeroAllocGeneratedAccessibility=Internal (#152) — gets its own internal class instead of
        // sharing the public ResilienceServiceCollectionExtensions.
        sb.AppendLine(model.EmitPublicEntryPoints
            ? "public static partial class ResilienceServiceCollectionExtensions"
            : "internal static partial class InternalResilienceServiceCollectionExtensions");
        sb.AppendLine("{");

        // The policies alone, for hosts that build the proxy themselves. TryAdd: an instance the
        // application registered first wins, and configure then does not run.
        sb.AppendLine($"    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection Add{name}ResiliencePolicies(");
        sb.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,");
        sb.AppendLine($"        global::System.Action<global::System.IServiceProvider, {policies}>? configure = null)");
        sb.AppendLine("    {");
        sb.AppendLine($"        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<{policies}>(services, sp =>");
        sb.AppendLine("        {");
        sb.AppendLine($"            var policies = new {policies}();");
        sb.AppendLine("            configure?.Invoke(sp, policies);");
        sb.AppendLine("            return policies;");
        sb.AppendLine("        });");
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine();

        WriteAddResilience(sb, model, withConfigure: false);
        sb.AppendLine();
        WriteAddResilience(sb, model, withConfigure: true);

        sb.AppendLine("}");
    }

    private static void WriteAddResilience(StringBuilder sb, ResilienceModel model, bool withConfigure)
    {
        var name = ResilienceGenerator.ServiceName(model.InterfaceName);
        var policies = model.PoliciesClassName;

        sb.AppendLine($"    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection Add{name}Resilience<");
        // IL2091: TImpl flows into AddTransient<T> which requires PublicConstructors.
        sb.AppendLine("        [global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(");
        sb.AppendLine("            global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)]");
        sb.AppendLine("        TImpl>(");
        if (withConfigure)
        {
            sb.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,");
            sb.AppendLine($"        global::System.Action<global::System.IServiceProvider, {policies}> configure)");
        }
        else
        {
            sb.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        }
        sb.AppendLine($"        where TImpl : class, {model.InterfaceFqn}");
        sb.AppendLine("    {");
        if (withConfigure)
            sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(configure);");
        sb.AppendLine("        services.AddTransient<TImpl>();");
        sb.AppendLine(withConfigure
            ? $"        services.Add{name}ResiliencePolicies(configure);"
            : $"        services.Add{name}ResiliencePolicies();");
        sb.AppendLine($"        services.AddTransient<{model.InterfaceFqn}>(sp => new {model.InterfaceName}ResilienceProxy(");
        sb.AppendLine($"            sp.GetRequiredService<TImpl>(), sp.GetRequiredService<{policies}>()));");
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
    }
}
