namespace ZeroAlloc.Resilience.Generator;

using System.Linq;
using System.Text;

internal static class ResilienceWriter
{
    public static string Write(ResilienceModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using ZeroAlloc.Resilience;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();

        if (model.Namespace is not null)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        WriteProxy(sb, model);
        sb.AppendLine();
        WriteDiExtension(sb, model);

        return sb.ToString();
    }

    private static void WriteProxy(StringBuilder sb, ResilienceModel model)
    {
        var hasRetry   = model.Methods.Any(static m => m.Retry is not null);
        var hasTimeout = model.Methods.Any(static m => m.Timeout is not null);
        var hasRate    = model.Methods.Any(static m => m.RateLimit is not null);
        var hasCb      = model.Methods.Any(static m => m.CircuitBreaker is not null);

        sb.AppendLine($"internal sealed class {model.InterfaceName}ResilienceProxy : {model.InterfaceFqn}");
        sb.AppendLine("{");
        sb.AppendLine($"    private readonly {model.InterfaceFqn} _inner;");
        if (hasRetry)   sb.AppendLine("    private readonly global::ZeroAlloc.Resilience.RetryPolicy _retry;");
        if (hasTimeout) sb.AppendLine("    private readonly global::ZeroAlloc.Resilience.TimeoutPolicy _timeout;");
        if (hasRate)    sb.AppendLine("    private readonly global::ZeroAlloc.Resilience.RateLimiter _rateLimiter;");
        if (hasCb)      sb.AppendLine("    private readonly global::ZeroAlloc.Resilience.CircuitBreakerPolicy _circuitBreaker;");
        sb.AppendLine();

        // Constructor
        sb.Append($"    public {model.InterfaceName}ResilienceProxy({model.InterfaceFqn} inner");
        if (hasRetry)   sb.Append(", global::ZeroAlloc.Resilience.RetryPolicy retry");
        if (hasTimeout) sb.Append(", global::ZeroAlloc.Resilience.TimeoutPolicy timeout");
        if (hasRate)    sb.Append(", global::ZeroAlloc.Resilience.RateLimiter rateLimiter");
        if (hasCb)      sb.Append(", global::ZeroAlloc.Resilience.CircuitBreakerPolicy circuitBreaker");
        sb.AppendLine(")");
        sb.AppendLine("    {");
        sb.AppendLine("        _inner = inner;");
        if (hasRetry)   sb.AppendLine("        _retry = retry;");
        if (hasTimeout) sb.AppendLine("        _timeout = timeout;");
        if (hasRate)    sb.AppendLine("        _rateLimiter = rateLimiter;");
        if (hasCb)      sb.AppendLine("        _circuitBreaker = circuitBreaker;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Policy-wrapped methods
        foreach (var method in model.Methods)
            WriteMethod(sb, method);

        // Passthrough methods (no policy — direct delegation)
        foreach (var method in model.PassthroughMethods)
            WritePassthrough(sb, method);

        sb.AppendLine("}");
    }

    private static void WriteMethod(StringBuilder sb, MethodModel method)
    {
        var asyncKw = method.IsAsync ? "async " : "";
        sb.AppendLine($"    public {asyncKw}{method.ReturnTypeFqn} {method.Name}({method.ParameterList})");
        sb.AppendLine("    {");

        // 1. Rate limit
        if (method.RateLimit is not null)
        {
            sb.AppendLine("        if (!_rateLimiter.TryAcquire())");
            if (method.ReturnsResult)
                sb.AppendLine($"            return global::ZeroAlloc.Results.Result.Failure<{method.InnerReturnType}>(\"Rate limit exceeded.\");");
            else
                sb.AppendLine("            throw new global::ZeroAlloc.Resilience.ResilienceException(global::ZeroAlloc.Resilience.ResiliencePolicy.RateLimit, \"Rate limit exceeded.\");");
            sb.AppendLine();
        }

        // 2. Circuit breaker check
        if (method.CircuitBreaker is not null)
        {
            sb.AppendLine("        if (!_circuitBreaker.CanExecute())");
            sb.AppendLine("        {");
            if (method.FallbackMethodName is not null)
            {
                var awaitFb = method.IsAsync ? "await " : "";
                var configFb = method.IsAsync ? ".ConfigureAwait(false)" : "";
                sb.AppendLine($"            return {awaitFb}_inner.{method.FallbackMethodName}({method.ArgumentList}){configFb};");
            }
            else if (method.ReturnsResult)
                sb.AppendLine($"            return global::ZeroAlloc.Results.Result.Failure<{method.InnerReturnType}>(\"Circuit breaker is open.\");");
            else
                sb.AppendLine("            throw new global::ZeroAlloc.Resilience.ResilienceException(global::ZeroAlloc.Resilience.ResiliencePolicy.CircuitBreaker, \"Circuit breaker is open.\");");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // 3. Total timeout CTS
        bool hasTotalTimeout = method.Timeout is not null;
        if (hasTotalTimeout)
        {
            if (method.CancellationTokenParamName is not null)
                sb.AppendLine($"        using var __totalCts = global::System.Threading.CancellationTokenSource.CreateLinkedTokenSource({method.CancellationTokenParamName});");
            else
                sb.AppendLine("        using var __totalCts = new global::System.Threading.CancellationTokenSource();");
            sb.AppendLine($"        __totalCts.CancelAfter({method.Timeout!.TotalMs});");
            sb.AppendLine();
        }

        // 4. Retry loop or single call
        if (method.Retry is not null)
        {
            WriteRetryLoop(sb, method, hasTotalTimeout);
        }
        else
        {
            WriteSingleCall(sb, method, hasTotalTimeout);
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void WriteRetryLoop(StringBuilder sb, MethodModel method, bool hasTotalTimeout)
    {
        var retry = method.Retry!;
        var awaitKw = method.IsAsync ? "await " : "";
        var configKw = method.IsAsync ? ".ConfigureAwait(false)" : "";

        sb.AppendLine("        global::System.Exception? __lastEx = null;");
        sb.AppendLine("        for (int __attempt = 0; __attempt < _retry.MaxAttempts; __attempt++)");
        sb.AppendLine("        {");

        // Per-attempt timeout CTS
        if (retry.PerAttemptTimeoutMs > 0 && method.HasCancellationToken)
        {
            var innerToken = hasTotalTimeout ? "__totalCts.Token" : method.CancellationTokenParamName ?? "default";
            sb.AppendLine($"            using var __attemptCts = global::System.Threading.CancellationTokenSource.CreateLinkedTokenSource({innerToken});");
            sb.AppendLine("            __attemptCts.CancelAfter(_retry.PerAttemptTimeoutMs);");
            sb.AppendLine("            var __ct = __attemptCts.Token;");
        }
        else if (hasTotalTimeout)
        {
            sb.AppendLine("            var __ct = __totalCts.Token;");
        }
        else if (method.HasCancellationToken)
        {
            sb.AppendLine($"            var __ct = {method.CancellationTokenParamName ?? "default"};");
        }

        sb.AppendLine("            try");
        sb.AppendLine("            {");
        var callArgs = method.HasCancellationToken ? method.ArgumentListWithToken : method.ArgumentList;
        sb.AppendLine($"                var __result = {awaitKw}_inner.{method.Name}({callArgs}){configKw};");
        if (method.CircuitBreaker is not null)
            sb.AppendLine("                _circuitBreaker.OnSuccess();");
        sb.AppendLine("                return __result;");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (global::System.Exception __ex)");
        sb.AppendLine("            {");
        sb.AppendLine("                __lastEx = __ex;");
        if (method.CircuitBreaker is not null)
            sb.AppendLine("                _circuitBreaker.OnFailure(__ex);");
        if (hasTotalTimeout)
            sb.AppendLine("                if (__totalCts.IsCancellationRequested) break;");
        sb.AppendLine("                if (__attempt == _retry.MaxAttempts - 1) break;");
        if (method.IsAsync)
        {
            var delayToken = hasTotalTimeout ? ", __totalCts.Token" : "";
            sb.AppendLine($"                await global::System.Threading.Tasks.Task.Delay(_retry.GetBackoffMs(__attempt){delayToken}).ConfigureAwait(false);");
        }
        else
        {
            sb.AppendLine("                global::System.Threading.Thread.Sleep(_retry.GetBackoffMs(__attempt));");
        }
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        // All attempts exhausted");
        if (method.ReturnsResult)
            sb.AppendLine($"        return global::ZeroAlloc.Results.Result.Failure<{method.InnerReturnType}>(__lastEx?.Message ?? \"All retry attempts failed.\");");
        else
            sb.AppendLine("        throw new global::ZeroAlloc.Resilience.ResilienceException(global::ZeroAlloc.Resilience.ResiliencePolicy.Retry, \"All retry attempts failed.\", __lastEx);");
    }

    private static void WriteSingleCall(StringBuilder sb, MethodModel method, bool hasTotalTimeout)
    {
        var awaitKw = method.IsAsync ? "await " : "";
        var configKw = method.IsAsync ? ".ConfigureAwait(false)" : "";

        string callArgs;
        if (hasTotalTimeout && method.HasCancellationToken)
        {
            // ArgumentListWithToken has __ct in place of the CT param — define __ct = __totalCts.Token
            sb.AppendLine("        var __ct = __totalCts.Token;");
            callArgs = method.ArgumentListWithToken;
        }
        else
        {
            callArgs = method.ArgumentList;
        }

        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine($"            var __result = {awaitKw}_inner.{method.Name}({callArgs}){configKw};");
        if (method.CircuitBreaker is not null)
            sb.AppendLine("            _circuitBreaker.OnSuccess();");
        sb.AppendLine("            return __result;");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (global::System.Exception __ex)");
        sb.AppendLine("        {");
        if (method.CircuitBreaker is not null)
            sb.AppendLine("            _circuitBreaker.OnFailure(__ex);");
        if (method.ReturnsResult)
            sb.AppendLine($"            return global::ZeroAlloc.Results.Result.Failure<{method.InnerReturnType}>(__ex.Message);");
        else
            sb.AppendLine("            throw;");
        sb.AppendLine("        }");
    }

    private static void WritePassthrough(StringBuilder sb, PassthroughMethodModel method)
    {
        var awaitKw = method.IsAsync ? "await " : "";
        var configKw = method.IsAsync ? ".ConfigureAwait(false)" : "";
        var asyncKw = method.IsAsync ? "async " : "";
        sb.AppendLine($"    public {asyncKw}{method.ReturnTypeFqn} {method.Name}({method.ParameterList})");
        sb.AppendLine($"        => {awaitKw}_inner.{method.Name}({method.ArgumentList}){configKw};");
        sb.AppendLine();
    }

    private static void WriteDiExtension(StringBuilder sb, ResilienceModel model)
    {
        var hasRetry   = model.Methods.Any(static m => m.Retry is not null);
        var hasTimeout = model.Methods.Any(static m => m.Timeout is not null);
        var hasRate    = model.Methods.Any(static m => m.RateLimit is not null);
        var hasCb      = model.Methods.Any(static m => m.CircuitBreaker is not null);

        var retry   = model.ClassRetry   ?? model.Methods.FirstOrDefault(static m => m.Retry is not null)?.Retry;
        var timeout = model.ClassTimeout ?? model.Methods.FirstOrDefault(static m => m.Timeout is not null)?.Timeout;
        var rate    = model.ClassRateLimit ?? model.Methods.FirstOrDefault(static m => m.RateLimit is not null)?.RateLimit;
        var cb      = model.ClassCircuitBreaker ?? model.Methods.FirstOrDefault(static m => m.CircuitBreaker is not null)?.CircuitBreaker;

        sb.AppendLine("public static partial class ResilienceServiceCollectionExtensions");
        sb.AppendLine("{");
        sb.AppendLine($"    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection Add{model.InterfaceName.TrimStart('I')}Resilience<TImpl>(");
        sb.AppendLine($"        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine($"        where TImpl : class, {model.InterfaceFqn}");
        sb.AppendLine("    {");
        sb.AppendLine("        services.AddTransient<TImpl>();");

        if (hasRetry && retry is not null)
            sb.AppendLine($"        services.AddSingleton(new global::ZeroAlloc.Resilience.RetryPolicy({retry.MaxAttempts}, {retry.BackoffMs}, {(retry.Jitter ? "true" : "false")}, {retry.PerAttemptTimeoutMs}));");
        if (hasTimeout && timeout is not null)
            sb.AppendLine($"        services.AddSingleton(new global::ZeroAlloc.Resilience.TimeoutPolicy({timeout.TotalMs}));");
        if (hasRate && rate is not null)
            sb.AppendLine($"        services.AddSingleton(new global::ZeroAlloc.Resilience.RateLimiter({rate.MaxPerSecond}, {rate.BurstSize}, global::ZeroAlloc.Resilience.RateLimitScope.{rate.Scope}));");
        if (hasCb && cb is not null)
            sb.AppendLine($"        services.AddSingleton(new global::ZeroAlloc.Resilience.CircuitBreakerPolicy({cb.MaxFailures}, {cb.ResetMs}, {cb.HalfOpenProbes}));");

        sb.Append($"        services.AddTransient<{model.InterfaceFqn}>(sp => new {model.InterfaceName}ResilienceProxy(");
        sb.Append("sp.GetRequiredService<TImpl>()");
        if (hasRetry)   sb.Append(", sp.GetRequiredService<global::ZeroAlloc.Resilience.RetryPolicy>()");
        if (hasTimeout) sb.Append(", sp.GetRequiredService<global::ZeroAlloc.Resilience.TimeoutPolicy>()");
        if (hasRate)    sb.Append(", sp.GetRequiredService<global::ZeroAlloc.Resilience.RateLimiter>()");
        if (hasCb)      sb.Append(", sp.GetRequiredService<global::ZeroAlloc.Resilience.CircuitBreakerPolicy>()");
        sb.AppendLine("));");

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

}
