//HintName: T_IExternalService.Resilience.g.cs
// <auto-generated />
#nullable enable

using System.Threading;
using System.Threading.Tasks;
using ZeroAlloc.Resilience;
using Microsoft.Extensions.DependencyInjection;

namespace T;

public sealed class ExternalServiceResiliencePolicies
{
    public global::ZeroAlloc.Resilience.RetryPolicy Retry { get; set; } = new global::ZeroAlloc.Resilience.RetryPolicy(3, 200, true, 1000);
    public global::ZeroAlloc.Resilience.TimeoutPolicy Timeout { get; set; } = new global::ZeroAlloc.Resilience.TimeoutPolicy(5000);
    public global::ZeroAlloc.Resilience.RateLimiter RateLimiter { get; set; } = new global::ZeroAlloc.Resilience.RateLimiter(100, 10, global::ZeroAlloc.Resilience.RateLimitScope.Shared);
    public global::ZeroAlloc.Resilience.CircuitBreakerPolicy CircuitBreaker { get; set; } = new global::ZeroAlloc.Resilience.CircuitBreakerPolicy(5, 1000, 1);
}

internal sealed class IExternalServiceResilienceProxy : global::T.IExternalService
{
    private readonly global::T.IExternalService _inner;
    private readonly global::ZeroAlloc.Resilience.RetryPolicy _retry;
    private readonly global::ZeroAlloc.Resilience.TimeoutPolicy _timeout;
    private readonly global::ZeroAlloc.Resilience.RateLimiter _rateLimiter;
    private readonly global::ZeroAlloc.Resilience.CircuitBreakerPolicy _circuitBreaker;

    public IExternalServiceResilienceProxy(global::T.IExternalService inner, ExternalServiceResiliencePolicies policies)
    {
        global::System.ArgumentNullException.ThrowIfNull(inner);
        global::System.ArgumentNullException.ThrowIfNull(policies);
        _inner = inner;
        _retry = (policies.Retry ?? throw new global::System.ArgumentException("ExternalServiceResiliencePolicies.Retry is null.", nameof(policies)));
        _timeout = (policies.Timeout ?? throw new global::System.ArgumentException("ExternalServiceResiliencePolicies.Timeout is null.", nameof(policies)));
        _rateLimiter = (policies.RateLimiter ?? throw new global::System.ArgumentException("ExternalServiceResiliencePolicies.RateLimiter is null.", nameof(policies))).ForProxyInstance();
        _circuitBreaker = (policies.CircuitBreaker ?? throw new global::System.ArgumentException("ExternalServiceResiliencePolicies.CircuitBreaker is null.", nameof(policies)));
    }

    public async global::System.Threading.Tasks.ValueTask<string> FetchAsync(string id, global::System.Threading.CancellationToken ct)
    {
        if (!_rateLimiter.TryAcquire())
            throw new global::ZeroAlloc.Resilience.ResilienceException(global::ZeroAlloc.Resilience.ResiliencePolicy.RateLimit, "Rate limit exceeded.");

        if (!_circuitBreaker.CanExecute())
        {
            throw new global::ZeroAlloc.Resilience.ResilienceException(global::ZeroAlloc.Resilience.ResiliencePolicy.CircuitBreaker, "Circuit breaker is open.");
        }

        using var __totalCts = global::System.Threading.CancellationTokenSource.CreateLinkedTokenSource(ct);
        __totalCts.CancelAfter(_timeout.TotalMs);

        global::System.Exception? __lastEx = null;
        for (int __attempt = 0; __attempt < _retry.MaxAttempts; __attempt++)
        {
            using var __attemptCts = _retry.PerAttemptTimeoutMs > 0
                ? global::System.Threading.CancellationTokenSource.CreateLinkedTokenSource(__totalCts.Token)
                : null;
            __attemptCts?.CancelAfter(_retry.PerAttemptTimeoutMs);
            var __ct = __attemptCts?.Token ?? __totalCts.Token;
            try
            {
                var __result = await _inner.FetchAsync(id, __ct).ConfigureAwait(false);
                _circuitBreaker.OnSuccess();
                return __result;
            }
            catch (global::System.Exception __ex)
            {
                __lastEx = __ex;
                _circuitBreaker.OnFailure(__ex);
                if (__totalCts.IsCancellationRequested) break;
                if (__attempt == _retry.MaxAttempts - 1) break;
                await global::System.Threading.Tasks.Task.Delay(_retry.GetBackoffMs(__attempt), __totalCts.Token).ConfigureAwait(false);
            }
        }
        // All attempts exhausted
        throw new global::ZeroAlloc.Resilience.ResilienceException(global::ZeroAlloc.Resilience.ResiliencePolicy.Retry, "All retry attempts failed.", __lastEx);
    }

    public async global::System.Threading.Tasks.ValueTask<string> FetchFallback(string id, global::System.Threading.CancellationToken ct)
    {
        if (!_rateLimiter.TryAcquire())
            throw new global::ZeroAlloc.Resilience.ResilienceException(global::ZeroAlloc.Resilience.ResiliencePolicy.RateLimit, "Rate limit exceeded.");

        if (!_circuitBreaker.CanExecute())
        {
            throw new global::ZeroAlloc.Resilience.ResilienceException(global::ZeroAlloc.Resilience.ResiliencePolicy.CircuitBreaker, "Circuit breaker is open.");
        }

        using var __totalCts = global::System.Threading.CancellationTokenSource.CreateLinkedTokenSource(ct);
        __totalCts.CancelAfter(_timeout.TotalMs);

        global::System.Exception? __lastEx = null;
        for (int __attempt = 0; __attempt < _retry.MaxAttempts; __attempt++)
        {
            using var __attemptCts = _retry.PerAttemptTimeoutMs > 0
                ? global::System.Threading.CancellationTokenSource.CreateLinkedTokenSource(__totalCts.Token)
                : null;
            __attemptCts?.CancelAfter(_retry.PerAttemptTimeoutMs);
            var __ct = __attemptCts?.Token ?? __totalCts.Token;
            try
            {
                var __result = await _inner.FetchFallback(id, __ct).ConfigureAwait(false);
                _circuitBreaker.OnSuccess();
                return __result;
            }
            catch (global::System.Exception __ex)
            {
                __lastEx = __ex;
                _circuitBreaker.OnFailure(__ex);
                if (__totalCts.IsCancellationRequested) break;
                if (__attempt == _retry.MaxAttempts - 1) break;
                await global::System.Threading.Tasks.Task.Delay(_retry.GetBackoffMs(__attempt), __totalCts.Token).ConfigureAwait(false);
            }
        }
        // All attempts exhausted
        throw new global::ZeroAlloc.Resilience.ResilienceException(global::ZeroAlloc.Resilience.ResiliencePolicy.Retry, "All retry attempts failed.", __lastEx);
    }

}

public static partial class ResilienceServiceCollectionExtensions
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddExternalServiceResiliencePolicies(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        global::System.Action<global::System.IServiceProvider, ExternalServiceResiliencePolicies>? configure = null)
    {
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<ExternalServiceResiliencePolicies>(services, sp =>
        {
            var policies = new ExternalServiceResiliencePolicies();
            configure?.Invoke(sp, policies);
            return policies;
        });
        return services;
    }

    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddExternalServiceResilience<
        [global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(
            global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)]
        TImpl>(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        where TImpl : class, global::T.IExternalService
    {
        services.AddTransient<TImpl>();
        services.AddExternalServiceResiliencePolicies();
        services.AddTransient<global::T.IExternalService>(sp => new IExternalServiceResilienceProxy(
            sp.GetRequiredService<TImpl>(), sp.GetRequiredService<ExternalServiceResiliencePolicies>()));
        return services;
    }
}
