//HintName: T_IMyService.Resilience.g.cs
// <auto-generated />
#nullable enable

using System.Threading;
using System.Threading.Tasks;
using ZeroAlloc.Resilience;
using Microsoft.Extensions.DependencyInjection;

namespace T;

public sealed class MyServiceResiliencePolicies
{
    public global::ZeroAlloc.Resilience.CircuitBreakerPolicy CircuitBreaker { get; set; } = new global::ZeroAlloc.Resilience.CircuitBreakerPolicy(3, 500, 1);
}

internal sealed class IMyServiceResilienceProxy : global::T.IMyService
{
    private readonly global::T.IMyService _inner;
    private readonly global::ZeroAlloc.Resilience.CircuitBreakerPolicy _circuitBreaker;

    public IMyServiceResilienceProxy(global::T.IMyService inner, MyServiceResiliencePolicies policies)
    {
        global::System.ArgumentNullException.ThrowIfNull(inner);
        global::System.ArgumentNullException.ThrowIfNull(policies);
        _inner = inner;
        _circuitBreaker = (policies.CircuitBreaker ?? throw new global::System.ArgumentException("MyServiceResiliencePolicies.CircuitBreaker is null.", nameof(policies)));
    }

    public async global::System.Threading.Tasks.ValueTask<string> FetchAsync(string id, global::System.Threading.CancellationToken ct)
    {
        if (!_circuitBreaker.CanExecute())
        {
            return await _inner.FetchFallback(id, ct).ConfigureAwait(false);
        }

        try
        {
            var __result = await _inner.FetchAsync(id, ct).ConfigureAwait(false);
            _circuitBreaker.OnSuccess();
            return __result;
        }
        catch (global::System.Exception __ex)
        {
            _circuitBreaker.OnFailure(__ex);
            throw;
        }
    }

    public async global::System.Threading.Tasks.ValueTask<string> FetchFallback(string id, global::System.Threading.CancellationToken ct)
    {
        if (!_circuitBreaker.CanExecute())
        {
            return await _inner.FetchFallback(id, ct).ConfigureAwait(false);
        }

        try
        {
            var __result = await _inner.FetchFallback(id, ct).ConfigureAwait(false);
            _circuitBreaker.OnSuccess();
            return __result;
        }
        catch (global::System.Exception __ex)
        {
            _circuitBreaker.OnFailure(__ex);
            throw;
        }
    }

}

public static partial class ResilienceServiceCollectionExtensions
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddMyServiceResiliencePolicies(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        global::System.Action<global::System.IServiceProvider, MyServiceResiliencePolicies>? configure = null)
    {
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<MyServiceResiliencePolicies>(services, sp =>
        {
            var policies = new MyServiceResiliencePolicies();
            configure?.Invoke(sp, policies);
            return policies;
        });
        return services;
    }

    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddMyServiceResilience<
        [global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(
            global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)]
        TImpl>(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        where TImpl : class, global::T.IMyService
    {
        services.AddTransient<TImpl>();
        services.AddMyServiceResiliencePolicies();
        services.AddTransient<global::T.IMyService>(sp => new IMyServiceResilienceProxy(
            sp.GetRequiredService<TImpl>(), sp.GetRequiredService<MyServiceResiliencePolicies>()));
        return services;
    }
}
