//HintName: T_IExternalService.Resilience.g.cs
// <auto-generated />
#nullable enable

using System.Threading;
using System.Threading.Tasks;
using ZeroAlloc.Resilience;
using Microsoft.Extensions.DependencyInjection;

namespace T;

internal sealed class IExternalServiceResilienceProxy : global::T.IExternalService
{
    private readonly global::T.IExternalService _inner;
    private readonly global::ZeroAlloc.Resilience.RetryPolicy _retry;
    private readonly global::ZeroAlloc.Resilience.TimeoutPolicy _timeout;
    private readonly global::ZeroAlloc.Resilience.RateLimiter _rateLimiter;
    private readonly global::ZeroAlloc.Resilience.CircuitBreakerPolicy _circuitBreaker;

    public IExternalServiceResilienceProxy(global::T.IExternalService inner, global::ZeroAlloc.Resilience.RetryPolicy retry, global::ZeroAlloc.Resilience.TimeoutPolicy timeout, global::ZeroAlloc.Resilience.RateLimiter rateLimiter, global::ZeroAlloc.Resilience.CircuitBreakerPolicy circuitBreaker)
    {
        _inner = inner;
        _retry = retry;
        _timeout = timeout;
        _rateLimiter = rateLimiter;
        _circuitBreaker = circuitBreaker;
    }

    public async global::System.Threading.Tasks.ValueTask<string> FetchAsync(string id, global::System.Threading.CancellationToken ct)
    {
        if (!_rateLimiter.TryAcquire())
            throw new global::ZeroAlloc.Resilience.ResilienceException(global::ZeroAlloc.Resilience.ResiliencePolicy.RateLimit, "Rate limit exceeded.");

        if (!_circuitBreaker.CanExecute())
        {
            throw new global::ZeroAlloc.Resilience.ResilienceException(global::ZeroAlloc.Resilience.ResiliencePolicy.CircuitBreaker, "Circuit breaker is open.");
        }

        using var __totalCts = global::System.Threading.CancellationTokenSource.CreateLinkedTokenSource(ct);
        __totalCts.CancelAfter(5000);

        global::System.Exception? __lastEx = null;
        for (int __attempt = 0; __attempt < 3; __attempt++)
        {
            using var __attemptCts = global::System.Threading.CancellationTokenSource.CreateLinkedTokenSource(__totalCts.Token);
            __attemptCts.CancelAfter(1000);
            var __ct = __attemptCts.Token;
            try
            {
                var __result = await _inner.FetchAsync(id, __ct).ConfigureAwait(false);
                _circuitBreaker.OnSuccess();
                return __result;
            }
            catch (global::System.Exception __ex)
            {
                __lastEx = __ex;
                _circuitBreaker.OnFailure(__ex);
                if (__totalCts.IsCancellationRequested) break;
                if (__attempt == 2) break;
                await global::System.Threading.Tasks.Task.Delay(200 * (1 << __attempt) + global::System.Random.Shared.Next(0, global::System.Math.Max(1, 200 * (1 << __attempt) / 2)), __totalCts.Token).ConfigureAwait(false);
            }
        }
        // All attempts exhausted
        throw new global::ZeroAlloc.Resilience.ResilienceException(global::ZeroAlloc.Resilience.ResiliencePolicy.Retry, "All retry attempts failed.", __lastEx);
    }

    public async global::System.Threading.Tasks.ValueTask<string> FetchFallback(string id, global::System.Threading.CancellationToken ct)
    {
        if (!_rateLimiter.TryAcquire())
            throw new global::ZeroAlloc.Resilience.ResilienceException(global::ZeroAlloc.Resilience.ResiliencePolicy.RateLimit, "Rate limit exceeded.");

        if (!_circuitBreaker.CanExecute())
        {
            throw new global::ZeroAlloc.Resilience.ResilienceException(global::ZeroAlloc.Resilience.ResiliencePolicy.CircuitBreaker, "Circuit breaker is open.");
        }

        using var __totalCts = global::System.Threading.CancellationTokenSource.CreateLinkedTokenSource(ct);
        __totalCts.CancelAfter(5000);

        global::System.Exception? __lastEx = null;
        for (int __attempt = 0; __attempt < 3; __attempt++)
        {
            using var __attemptCts = global::System.Threading.CancellationTokenSource.CreateLinkedTokenSource(__totalCts.Token);
            __attemptCts.CancelAfter(1000);
            var __ct = __attemptCts.Token;
            try
            {
                var __result = await _inner.FetchFallback(id, __ct).ConfigureAwait(false);
                _circuitBreaker.OnSuccess();
                return __result;
            }
            catch (global::System.Exception __ex)
            {
                __lastEx = __ex;
                _circuitBreaker.OnFailure(__ex);
                if (__totalCts.IsCancellationRequested) break;
                if (__attempt == 2) break;
                await global::System.Threading.Tasks.Task.Delay(200 * (1 << __attempt) + global::System.Random.Shared.Next(0, global::System.Math.Max(1, 200 * (1 << __attempt) / 2)), __totalCts.Token).ConfigureAwait(false);
            }
        }
        // All attempts exhausted
        throw new global::ZeroAlloc.Resilience.ResilienceException(global::ZeroAlloc.Resilience.ResiliencePolicy.Retry, "All retry attempts failed.", __lastEx);
    }

}

public static partial class ResilienceServiceCollectionExtensions
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddExternalServiceResilience<
        [global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(
            global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)]
        TImpl>(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        where TImpl : class, global::T.IExternalService
    {
        services.AddTransient<TImpl>();
        services.AddSingleton(new global::ZeroAlloc.Resilience.RetryPolicy(3, 200, true, 1000));
        services.AddSingleton(new global::ZeroAlloc.Resilience.TimeoutPolicy(5000));
        services.AddSingleton(new global::ZeroAlloc.Resilience.RateLimiter(100, 10, global::ZeroAlloc.Resilience.RateLimitScope.Shared));
        services.AddSingleton(new global::ZeroAlloc.Resilience.CircuitBreakerPolicy(5, 1000, 1));
        services.AddTransient<global::T.IExternalService>(sp => new IExternalServiceResilienceProxy(sp.GetRequiredService<TImpl>(), sp.GetRequiredService<global::ZeroAlloc.Resilience.RetryPolicy>(), sp.GetRequiredService<global::ZeroAlloc.Resilience.TimeoutPolicy>(), sp.GetRequiredService<global::ZeroAlloc.Resilience.RateLimiter>(), sp.GetRequiredService<global::ZeroAlloc.Resilience.CircuitBreakerPolicy>()));
        return services;
    }
}
