//HintName: T_IApi.Resilience.g.cs
// <auto-generated />
#nullable enable

using System.Threading;
using System.Threading.Tasks;
using ZeroAlloc.Resilience;
using Microsoft.Extensions.DependencyInjection;

namespace T;

public sealed class ApiResiliencePolicies
{
    public global::ZeroAlloc.Resilience.RetryPolicy Retry { get; set; } = new global::ZeroAlloc.Resilience.RetryPolicy(3, 100, false, 0);
}

internal sealed class IApiResilienceProxy : global::T.IApi
{
    private readonly global::T.IApi _inner;
    private readonly global::ZeroAlloc.Resilience.RetryPolicy _retry;

    public IApiResilienceProxy(global::T.IApi inner, ApiResiliencePolicies policies)
    {
        global::System.ArgumentNullException.ThrowIfNull(inner);
        global::System.ArgumentNullException.ThrowIfNull(policies);
        _inner = inner;
        _retry = (policies.Retry ?? throw new global::System.ArgumentException("ApiResiliencePolicies.Retry is null.", nameof(policies)));
    }

    public async global::System.Threading.Tasks.ValueTask<string> GetAsync(string id, global::System.Threading.CancellationToken ct)
    {
        global::System.Exception? __lastEx = null;
        for (int __attempt = 0; __attempt < _retry.MaxAttempts; __attempt++)
        {
            using var __attemptCts = _retry.PerAttemptTimeoutMs > 0
                ? global::System.Threading.CancellationTokenSource.CreateLinkedTokenSource(ct)
                : null;
            __attemptCts?.CancelAfter(_retry.PerAttemptTimeoutMs);
            var __ct = __attemptCts?.Token ?? ct;
            try
            {
                var __result = await _inner.GetAsync(id, __ct).ConfigureAwait(false);
                return __result;
            }
            catch (global::System.OperationCanceledException) when (ct.IsCancellationRequested)
            {
                throw;
            }
            catch (global::System.Exception __ex)
            {
                __lastEx = __ex;
                if (!global::T.IApi.IsTransient(__ex)) break;
                var __hint = global::T.IApi.RetryAfter(__ex);
                if (__attempt == _retry.MaxAttempts - 1) break;
                await global::System.Threading.Tasks.Task.Delay(_retry.GetDelayMs(__attempt, __hint), ct).ConfigureAwait(false);
            }
        }
        // All attempts exhausted
        throw new global::ZeroAlloc.Resilience.ResilienceException(global::ZeroAlloc.Resilience.ResiliencePolicy.Retry, "All retry attempts failed.", __lastEx);
    }

    public string Get(string id)
    {
        global::System.Exception? __lastEx = null;
        for (int __attempt = 0; __attempt < _retry.MaxAttempts; __attempt++)
        {
            try
            {
                var __result = _inner.Get(id);
                return __result;
            }
            catch (global::System.Exception __ex)
            {
                __lastEx = __ex;
                if (!global::T.IApi.IsTransient(__ex)) break;
                var __hint = global::T.IApi.RetryAfter(__ex);
                if (__attempt == _retry.MaxAttempts - 1) break;
                global::System.Threading.Thread.Sleep(_retry.GetDelayMs(__attempt, __hint));
            }
        }
        // All attempts exhausted
        throw new global::ZeroAlloc.Resilience.ResilienceException(global::ZeroAlloc.Resilience.ResiliencePolicy.Retry, "All retry attempts failed.", __lastEx);
    }

}

public static partial class ResilienceServiceCollectionExtensions
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddApiResiliencePolicies(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        global::System.Action<global::System.IServiceProvider, ApiResiliencePolicies>? configure = null)
    {
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<ApiResiliencePolicies>(services, sp =>
        {
            var policies = new ApiResiliencePolicies();
            configure?.Invoke(sp, policies);
            return policies;
        });
        return services;
    }

    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddApiResilience<
        [global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(
            global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)]
        TImpl>(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        where TImpl : class, global::T.IApi
    {
        services.AddTransient<TImpl>();
        services.AddApiResiliencePolicies();
        services.AddTransient<global::T.IApi>(sp => new IApiResilienceProxy(
            sp.GetRequiredService<TImpl>(), sp.GetRequiredService<ApiResiliencePolicies>()));
        return services;
    }

    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddApiResilience<
        [global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(
            global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)]
        TImpl>(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        global::System.Action<global::System.IServiceProvider, ApiResiliencePolicies> configure)
        where TImpl : class, global::T.IApi
    {
        global::System.ArgumentNullException.ThrowIfNull(configure);
        services.AddTransient<TImpl>();
        services.AddApiResiliencePolicies(configure);
        services.AddTransient<global::T.IApi>(sp => new IApiResilienceProxy(
            sp.GetRequiredService<TImpl>(), sp.GetRequiredService<ApiResiliencePolicies>()));
        return services;
    }
}
