//HintName: T_IMyService.Resilience.g.cs
// <auto-generated />
#nullable enable

using System.Threading;
using System.Threading.Tasks;
using ZeroAlloc.Resilience;
using Microsoft.Extensions.DependencyInjection;

namespace T;

internal sealed class IMyServiceResilienceProxy : global::T.IMyService
{
    private readonly global::T.IMyService _inner;
    private readonly global::ZeroAlloc.Resilience.CircuitBreakerPolicy _circuitBreaker;

    public IMyServiceResilienceProxy(global::T.IMyService inner, global::ZeroAlloc.Resilience.CircuitBreakerPolicy circuitBreaker)
    {
        _inner = inner;
        _circuitBreaker = circuitBreaker;
    }

    public async global::System.Threading.Tasks.ValueTask<string> FetchAsync(string id, global::System.Threading.CancellationToken ct)
    {
        if (!_circuitBreaker.CanExecute())
        {
            return await _inner.FetchFallback(id, ct).ConfigureAwait(false);
        }

        try
        {
            var __result = await _inner.FetchAsync(id, ct).ConfigureAwait(false);
            _circuitBreaker.OnSuccess();
            return __result;
        }
        catch (global::System.Exception __ex)
        {
            _circuitBreaker.OnFailure(__ex);
            throw;
        }
    }

    public async global::System.Threading.Tasks.ValueTask<string> FetchFallback(string id, global::System.Threading.CancellationToken ct)
    {
        if (!_circuitBreaker.CanExecute())
        {
            return await _inner.FetchFallback(id, ct).ConfigureAwait(false);
        }

        try
        {
            var __result = await _inner.FetchFallback(id, ct).ConfigureAwait(false);
            _circuitBreaker.OnSuccess();
            return __result;
        }
        catch (global::System.Exception __ex)
        {
            _circuitBreaker.OnFailure(__ex);
            throw;
        }
    }

}

public static partial class ResilienceServiceCollectionExtensions
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddMyServiceResilience<TImpl>(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        where TImpl : class, global::T.IMyService
    {
        services.AddTransient<TImpl>();
        services.AddSingleton(new global::ZeroAlloc.Resilience.CircuitBreakerPolicy(3, 500, 1));
        services.AddTransient<global::T.IMyService>(sp => new IMyServiceResilienceProxy(sp.GetRequiredService<TImpl>(), sp.GetRequiredService<global::ZeroAlloc.Resilience.CircuitBreakerPolicy>()));
        return services;
    }
}
