//HintName: T_IMyService.Resilience.g.cs
// <auto-generated />
#nullable enable

using System.Threading;
using System.Threading.Tasks;
using ZeroAlloc.Resilience;
using Microsoft.Extensions.DependencyInjection;

namespace T;

internal sealed class IMyServiceResilienceProxy : global::T.IMyService
{
    private readonly global::T.IMyService _inner;
    private readonly global::ZeroAlloc.Resilience.RetryPolicy _retry;

    public IMyServiceResilienceProxy(global::T.IMyService inner, global::ZeroAlloc.Resilience.RetryPolicy retry)
    {
        _inner = inner;
        _retry = retry;
    }

    public async global::System.Threading.Tasks.ValueTask<string> GetAsync(string id, global::System.Threading.CancellationToken ct)
    {
        global::System.Exception? __lastEx = null;
        for (int __attempt = 0; __attempt < _retry.MaxAttempts; __attempt++)
        {
            var __ct = ct;
            try
            {
                var __result = await _inner.GetAsync(id, __ct).ConfigureAwait(false);
                return __result;
            }
            catch (global::System.Exception __ex)
            {
                __lastEx = __ex;
                if (__attempt == _retry.MaxAttempts - 1) break;
                await global::System.Threading.Tasks.Task.Delay(_retry.GetBackoffMs(__attempt)).ConfigureAwait(false);
            }
        }
        // All attempts exhausted
        throw new global::ZeroAlloc.Resilience.ResilienceException(global::ZeroAlloc.Resilience.ResiliencePolicy.Retry, "All retry attempts failed.", __lastEx);
    }

}

public static partial class ResilienceServiceCollectionExtensions
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddMyServiceResilience<TImpl>(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        where TImpl : class, global::T.IMyService
    {
        services.AddTransient<TImpl>();
        services.AddSingleton(new global::ZeroAlloc.Resilience.RetryPolicy(3, 100, false, 0));
        services.AddTransient<global::T.IMyService>(sp => new IMyServiceResilienceProxy(sp.GetRequiredService<TImpl>(), sp.GetRequiredService<global::ZeroAlloc.Resilience.RetryPolicy>()));
        return services;
    }
}
