//HintName: T_IMyService.Resilience.g.cs
// <auto-generated />
#nullable enable

using System.Threading;
using System.Threading.Tasks;
using ZeroAlloc.Resilience;
using Microsoft.Extensions.DependencyInjection;

namespace T;

internal sealed class IMyServiceResilienceProxy : global::T.IMyService
{
    private readonly global::T.IMyService _inner;
    private readonly global::ZeroAlloc.Resilience.RetryPolicy _retry;
    private readonly global::ZeroAlloc.Resilience.TimeoutPolicy _timeout;

    public IMyServiceResilienceProxy(global::T.IMyService inner, global::ZeroAlloc.Resilience.RetryPolicy retry, global::ZeroAlloc.Resilience.TimeoutPolicy timeout)
    {
        _inner = inner;
        _retry = retry;
        _timeout = timeout;
    }

    public async global::System.Threading.Tasks.ValueTask<string> GetAsync(string id, global::System.Threading.CancellationToken ct)
    {
        using var __totalCts = global::System.Threading.CancellationTokenSource.CreateLinkedTokenSource(ct);
        __totalCts.CancelAfter(5000);

        global::System.Exception? __lastEx = null;
        for (int __attempt = 0; __attempt < 3; __attempt++)
        {
            var __ct = __totalCts.Token;
            try
            {
                var __result = await _inner.GetAsync(id, __ct).ConfigureAwait(false);
                return __result;
            }
            catch (global::System.Exception __ex)
            {
                __lastEx = __ex;
                if (__totalCts.IsCancellationRequested) break;
                if (__attempt == 2) break;
                await global::System.Threading.Tasks.Task.Delay(200 * (1 << __attempt), __totalCts.Token).ConfigureAwait(false);
            }
        }
        // All attempts exhausted
        throw new global::ZeroAlloc.Resilience.ResilienceException(global::ZeroAlloc.Resilience.ResiliencePolicy.Retry, "All retry attempts failed.", __lastEx);
    }

    public async global::System.Threading.Tasks.ValueTask PostAsync(string data, global::System.Threading.CancellationToken ct)
    {
        using var __totalCts = global::System.Threading.CancellationTokenSource.CreateLinkedTokenSource(ct);
        __totalCts.CancelAfter(500);

        global::System.Exception? __lastEx = null;
        for (int __attempt = 0; __attempt < 1; __attempt++)
        {
            var __ct = __totalCts.Token;
            try
            {
                var __result = await _inner.PostAsync(data, __ct).ConfigureAwait(false);
                return __result;
            }
            catch (global::System.Exception __ex)
            {
                __lastEx = __ex;
                if (__totalCts.IsCancellationRequested) break;
                if (__attempt == 0) break;
                await global::System.Threading.Tasks.Task.Delay(200 * (1 << __attempt), __totalCts.Token).ConfigureAwait(false);
            }
        }
        // All attempts exhausted
        throw new global::ZeroAlloc.Resilience.ResilienceException(global::ZeroAlloc.Resilience.ResiliencePolicy.Retry, "All retry attempts failed.", __lastEx);
    }

}

public static partial class ResilienceServiceCollectionExtensions
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddMyServiceResilience<TImpl>(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        where TImpl : class, global::T.IMyService
    {
        services.AddTransient<TImpl>();
        services.AddSingleton(new global::ZeroAlloc.Resilience.RetryPolicy(3, 200, false, 0));
        services.AddSingleton(new global::ZeroAlloc.Resilience.TimeoutPolicy(5000));
        services.AddTransient<global::T.IMyService>(sp => new IMyServiceResilienceProxy(sp.GetRequiredService<TImpl>(), sp.GetRequiredService<global::ZeroAlloc.Resilience.RetryPolicy>(), sp.GetRequiredService<global::ZeroAlloc.Resilience.TimeoutPolicy>()));
        return services;
    }
}
