//HintName: T_IMyService.Resilience.g.cs
// <auto-generated />
#nullable enable

using System.Threading;
using System.Threading.Tasks;
using ZeroAlloc.Resilience;
using Microsoft.Extensions.DependencyInjection;

namespace T;

public sealed class MyServiceResiliencePolicies
{
    public global::ZeroAlloc.Resilience.RetryPolicy Retry { get; set; } = new global::ZeroAlloc.Resilience.RetryPolicy(3, 100, false, 0);
}

internal sealed class IMyServiceResilienceProxy : global::T.IMyService
{
    private readonly global::T.IMyService _inner;
    private readonly global::ZeroAlloc.Resilience.RetryPolicy _retry;

    public IMyServiceResilienceProxy(global::T.IMyService inner, MyServiceResiliencePolicies policies)
    {
        global::System.ArgumentNullException.ThrowIfNull(inner);
        global::System.ArgumentNullException.ThrowIfNull(policies);
        _inner = inner;
        _retry = (policies.Retry ?? throw new global::System.ArgumentException("MyServiceResiliencePolicies.Retry is null.", nameof(policies)));
    }

    public string Get(string id, global::System.Threading.CancellationToken ct)
    {
        global::System.Exception? __lastEx = null;
        for (int __attempt = 0; __attempt < _retry.MaxAttempts; __attempt++)
        {
            using var __attemptCts = _retry.PerAttemptTimeoutMs > 0
                ? global::System.Threading.CancellationTokenSource.CreateLinkedTokenSource(ct)
                : null;
            __attemptCts?.CancelAfter(_retry.PerAttemptTimeoutMs);
            var __ct = __attemptCts?.Token ?? ct;
            try
            {
                var __result = _inner.Get(id, __ct);
                return __result;
            }
            catch (global::System.OperationCanceledException) when (ct.IsCancellationRequested)
            {
                throw;
            }
            catch (global::System.Exception __ex)
            {
                __lastEx = __ex;
                if (__attempt == _retry.MaxAttempts - 1) break;
                if (ct.CanBeCanceled)
                {
                    ct.WaitHandle.WaitOne(_retry.GetBackoffMs(__attempt));
                    ct.ThrowIfCancellationRequested();
                }
                else
                {
                    global::System.Threading.Thread.Sleep(_retry.GetBackoffMs(__attempt));
                }
            }
        }
        // All attempts exhausted
        throw new global::ZeroAlloc.Resilience.ResilienceException(global::ZeroAlloc.Resilience.ResiliencePolicy.Retry, "All retry attempts failed.", __lastEx);
    }

    public string GetWithoutToken(string id)
    {
        global::System.Exception? __lastEx = null;
        for (int __attempt = 0; __attempt < _retry.MaxAttempts; __attempt++)
        {
            try
            {
                var __result = _inner.GetWithoutToken(id);
                return __result;
            }
            catch (global::System.Exception __ex)
            {
                __lastEx = __ex;
                if (__attempt == _retry.MaxAttempts - 1) break;
                global::System.Threading.Thread.Sleep(_retry.GetBackoffMs(__attempt));
            }
        }
        // All attempts exhausted
        throw new global::ZeroAlloc.Resilience.ResilienceException(global::ZeroAlloc.Resilience.ResiliencePolicy.Retry, "All retry attempts failed.", __lastEx);
    }

}

public static partial class ResilienceServiceCollectionExtensions
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddMyServiceResiliencePolicies(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        global::System.Action<global::System.IServiceProvider, MyServiceResiliencePolicies>? configure = null)
    {
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<MyServiceResiliencePolicies>(services, sp =>
        {
            var policies = new MyServiceResiliencePolicies();
            configure?.Invoke(sp, policies);
            return policies;
        });
        return services;
    }

    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddMyServiceResilience<
        [global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(
            global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)]
        TImpl>(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        where TImpl : class, global::T.IMyService
    {
        services.AddTransient<TImpl>();
        services.AddMyServiceResiliencePolicies();
        services.AddTransient<global::T.IMyService>(sp => new IMyServiceResilienceProxy(
            sp.GetRequiredService<TImpl>(), sp.GetRequiredService<MyServiceResiliencePolicies>()));
        return services;
    }

    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddMyServiceResilience<
        [global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(
            global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)]
        TImpl>(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        global::System.Action<global::System.IServiceProvider, MyServiceResiliencePolicies> configure)
        where TImpl : class, global::T.IMyService
    {
        global::System.ArgumentNullException.ThrowIfNull(configure);
        services.AddTransient<TImpl>();
        services.AddMyServiceResiliencePolicies(configure);
        services.AddTransient<global::T.IMyService>(sp => new IMyServiceResilienceProxy(
            sp.GetRequiredService<TImpl>(), sp.GetRequiredService<MyServiceResiliencePolicies>()));
        return services;
    }
}
