//HintName: T_IApi.Resilience.g.cs
// <auto-generated />
#nullable enable

using System.Threading;
using System.Threading.Tasks;
using ZeroAlloc.Resilience;
using Microsoft.Extensions.DependencyInjection;

namespace T;

public sealed class ApiResiliencePolicies
{
    public global::ZeroAlloc.Resilience.RetryPolicy Retry { get; set; } = new global::ZeroAlloc.Resilience.RetryPolicy(3, 100, false, 0);
    public global::ZeroAlloc.Resilience.TimeoutPolicy Timeout { get; set; } = new global::ZeroAlloc.Resilience.TimeoutPolicy(5000);
    public global::ZeroAlloc.Resilience.CircuitBreakerPolicy CircuitBreaker { get; set; } = new global::ZeroAlloc.Resilience.CircuitBreakerPolicy(5, 1000, 1);
}

internal sealed class IApiResilienceProxy : global::T.IApi
{
    private readonly global::T.IApi _inner;
    private readonly global::ZeroAlloc.Resilience.RetryPolicy _retry;
    private readonly global::ZeroAlloc.Resilience.TimeoutPolicy _timeout;
    private readonly global::ZeroAlloc.Resilience.CircuitBreakerPolicy _circuitBreaker;

    public IApiResilienceProxy(global::T.IApi inner, ApiResiliencePolicies policies)
    {
        global::System.ArgumentNullException.ThrowIfNull(inner);
        global::System.ArgumentNullException.ThrowIfNull(policies);
        _inner = inner;
        _retry = (policies.Retry ?? throw new global::System.ArgumentException("ApiResiliencePolicies.Retry is null.", nameof(policies)));
        _timeout = (policies.Timeout ?? throw new global::System.ArgumentException("ApiResiliencePolicies.Timeout is null.", nameof(policies)));
        _circuitBreaker = (policies.CircuitBreaker ?? throw new global::System.ArgumentException("ApiResiliencePolicies.CircuitBreaker is null.", nameof(policies)));
    }

    public async global::System.Threading.Tasks.Task<global::ZeroAlloc.Results.Result<string>> GetAsync(string id, global::System.Threading.CancellationToken ct)
    {
        if (!_circuitBreaker.CanExecute())
        {
            return global::ZeroAlloc.Results.Result<string>.Failure("Circuit breaker is open.");
        }

        using var __totalCts = global::System.Threading.CancellationTokenSource.CreateLinkedTokenSource(ct);
        __totalCts.CancelAfter(_timeout.TotalMs);

        global::System.Exception? __lastEx = null;
        global::ZeroAlloc.Results.Result<string> __lastResult = default;
        bool __lastWasResult = false;
        for (int __attempt = 0; __attempt < _retry.MaxAttempts; __attempt++)
        {
            using var __attemptCts = _retry.PerAttemptTimeoutMs > 0
                ? global::System.Threading.CancellationTokenSource.CreateLinkedTokenSource(__totalCts.Token)
                : null;
            __attemptCts?.CancelAfter(_retry.PerAttemptTimeoutMs);
            var __ct = __attemptCts?.Token ?? __totalCts.Token;
            global::System.TimeSpan? __hint = null;
            try
            {
                __lastResult = await _inner.GetAsync(id, __ct).ConfigureAwait(false);
                __lastWasResult = true;
            }
            catch (global::System.OperationCanceledException) when (ct.IsCancellationRequested)
            {
                throw;
            }
            catch (global::System.Exception __ex)
            {
                __lastEx = __ex;
                __lastWasResult = false;
                _circuitBreaker.OnFailure(__ex);
            }
            if (__lastWasResult)
            {
                if (__lastResult.IsSuccess || !global::T.IApi.IsTransient(__lastResult.Error))
                {
                    _circuitBreaker.OnSuccess();
                    return __lastResult;
                }
                _circuitBreaker.OnFailure();
                __hint = global::T.IApi.RetryAfter(__lastResult.Error);
            }
            if (__totalCts.IsCancellationRequested)
            {
                ct.ThrowIfCancellationRequested();
                break;
            }
            if (__attempt == _retry.MaxAttempts - 1) break;
            await global::System.Threading.Tasks.Task.Delay(_retry.GetDelayMs(__attempt, __hint), __totalCts.Token)
                .ConfigureAwait(global::System.Threading.Tasks.ConfigureAwaitOptions.SuppressThrowing);
            if (__totalCts.IsCancellationRequested)
            {
                ct.ThrowIfCancellationRequested();
                break;
            }
        }
        // All attempts exhausted, or a failure that is not retried
        if (__lastWasResult) return __lastResult;
        return global::ZeroAlloc.Results.Result<string>.Failure(__lastEx?.Message ?? "All retry attempts failed.");
    }

}

public static partial class ResilienceServiceCollectionExtensions
{
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddApiResiliencePolicies(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        global::System.Action<global::System.IServiceProvider, ApiResiliencePolicies>? configure = null)
    {
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<ApiResiliencePolicies>(services, sp =>
        {
            var policies = new ApiResiliencePolicies();
            configure?.Invoke(sp, policies);
            return policies;
        });
        return services;
    }

    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddApiResilience<
        [global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(
            global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)]
        TImpl>(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        where TImpl : class, global::T.IApi
    {
        services.AddTransient<TImpl>();
        services.AddApiResiliencePolicies();
        services.AddTransient<global::T.IApi>(sp => new IApiResilienceProxy(
            sp.GetRequiredService<TImpl>(), sp.GetRequiredService<ApiResiliencePolicies>()));
        return services;
    }

    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddApiResilience<
        [global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(
            global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors)]
        TImpl>(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        global::System.Action<global::System.IServiceProvider, ApiResiliencePolicies> configure)
        where TImpl : class, global::T.IApi
    {
        global::System.ArgumentNullException.ThrowIfNull(configure);
        services.AddTransient<TImpl>();
        services.AddApiResiliencePolicies(configure);
        services.AddTransient<global::T.IApi>(sp => new IApiResilienceProxy(
            sp.GetRequiredService<TImpl>(), sp.GetRequiredService<ApiResiliencePolicies>()));
        return services;
    }
}
