using ZeroAlloc.StateMachine;

namespace ZeroAlloc.Resilience;

/// <summary>State values for the circuit breaker finite state machine.</summary>
public enum CircuitBreakerState   { Closed, Open, HalfOpen }

/// <summary>Trigger values for the circuit breaker finite state machine.</summary>
public enum CircuitBreakerTrigger { Trip, Probe, Success, FailInHalfOpen }

/// <summary>
/// Lock-free circuit breaker FSM: Closed → Open → HalfOpen → Closed.
/// Generated by ZeroAlloc.StateMachine (concurrent mode — all transitions via Interlocked.CompareExchange).
/// </summary>
[StateMachine(InitialState = nameof(CircuitBreakerState.Closed), Concurrent = true)]
[Transition<CircuitBreakerState, CircuitBreakerTrigger>(
    From = CircuitBreakerState.Closed,   On = CircuitBreakerTrigger.Trip,          To = CircuitBreakerState.Open)]
[Transition<CircuitBreakerState, CircuitBreakerTrigger>(
    From = CircuitBreakerState.Open,     On = CircuitBreakerTrigger.Probe,         To = CircuitBreakerState.HalfOpen)]
[Transition<CircuitBreakerState, CircuitBreakerTrigger>(
    From = CircuitBreakerState.HalfOpen, On = CircuitBreakerTrigger.Success,       To = CircuitBreakerState.Closed)]
[Transition<CircuitBreakerState, CircuitBreakerTrigger>(
    From = CircuitBreakerState.HalfOpen, On = CircuitBreakerTrigger.FailInHalfOpen, To = CircuitBreakerState.Open)]
public sealed partial class CircuitBreakerFsm { }
